//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeCustomGrouping
    {
        public long AttributeCustomGroupingID { get; set; }
        public Nullable<long> CustomGroupID { get; set; }
        public Nullable<long> DimTablePrimaryID { get; set; }
        public string DimTableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> LogID { get; set; }
    }
}
