//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseModel
    {
        public long ID { get; set; }
        public Nullable<long> PatientSer { get; set; }
        public Nullable<long> CourseSer { get; set; }
        public string CourseId { get; set; }
        public Nullable<System.DateTime> CourseStartDateTime { get; set; }
        public string ClinicalStatus { get; set; }
        public Nullable<System.DateTime> FirstTreatmentDate { get; set; }
        public Nullable<System.DateTime> LastTreatmentDate { get; set; }
        public Nullable<int> NoTxSessionPlanned { get; set; }
        public Nullable<int> NoTxSessionDelivered { get; set; }
        public Nullable<int> NoTxSessionRemaining { get; set; }
        public Nullable<double> DoseDelivered { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public string Comment { get; set; }
        public string CompletedByUserName { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public string TreatmentIntentType { get; set; }
        public Nullable<long> PhysicianIntentSer { get; set; }
        public Nullable<long> DiagnosisSer { get; set; }
        public Nullable<long> DimDxSiteID { get; set; }
    }
}
