//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cube_DimPhysicianOrder
    {
        public long FactPhysicianOrderID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string AppliedUser { get; set; }
        public Nullable<long> DimDateID_PhysicianOrderTimeFrame { get; set; }
        public Nullable<System.DateTime> VerbalApprovedDate { get; set; }
        public Nullable<System.DateTime> VerbarlApprovedDate { get; set; }
        public string VerbalUserName { get; set; }
        public string OrderType { get; set; }
        public string TimeFrame { get; set; }
        public string OrderCreatedByUser { get; set; }
        public string AppliedIndicator { get; set; }
        public Nullable<System.DateTime> AppliedDateTime { get; set; }
        public string AppliedText { get; set; }
        public string ApprovedOnFileIndicator { get; set; }
        public string CancelEntryIndicator { get; set; }
        public string CompletedIndicator { get; set; }
        public string GeneratedIndicator { get; set; }
        public string PlacerOrderNumber { get; set; }
        public string PlanAffectIndicator { get; set; }
        public string PhysicianOrderSheetDesc { get; set; }
        public Nullable<int> PhysicianOrderTimeFrame { get; set; }
        public Nullable<int> PhysicianOrderTime { get; set; }
        public Nullable<System.DateTime> POTimeFrameDateTime { get; set; }
        public string RecurringIndicator { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EnteredDateTime { get; set; }
        public string EnteredUser { get; set; }
        public string VerbalOrderValidEntryIndicator { get; set; }
        public string VerbalOrderApprovalFlag { get; set; }
        public Nullable<System.DateTime> VerbalApprovalDateTime { get; set; }
        public string VerbalApprovalText { get; set; }
        public string VerbalComment { get; set; }
        public string DisplaySourceType { get; set; }
        public Nullable<System.DateTime> VerbalDateTime { get; set; }
        public string VerbalText { get; set; }
        public string VerbalType { get; set; }
        public string VerbalTypeDesc { get; set; }
        public string PhysicianOrderDescription { get; set; }
        public string PhysicianOrderDetails { get; set; }
        public string PhysicianOrderCategory { get; set; }
        public string PhysicianOrderDescText { get; set; }
        public string TreatmentPlanName { get; set; }
        public string TreatmentPlanVersionNumber { get; set; }
        public Nullable<System.DateTime> TreatmentPlanInitDateTime { get; set; }
        public string ExternalTreatmentPlanName { get; set; }
    }
}
