//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cube_VisitNotes
    {
        public long FactVisitNoteID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<System.DateTime> DateVisitNote { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string UserOverride { get; set; }
        public string CreaterFullName { get; set; }
        public string AuthorFullName { get; set; }
        public string AuthorOrgFullName { get; set; }
        public string ApprovedByFullName { get; set; }
        public string SupervisedByFullName { get; set; }
        public string SignedByFullName { get; set; }
        public string CertByFullName { get; set; }
        public string NoteType { get; set; }
        public string PropType { get; set; }
        public string VisitNoteText { get; set; }
        public string ApprovedFlag { get; set; }
        public string DictatedFlag { get; set; }
        public string OverrideUserId { get; set; }
        public string OverrideText { get; set; }
        public string ValidIndicator { get; set; }
        public string PrivateIndicator { get; set; }
        public string DisciplineType { get; set; }
        public string GeneratedIndicator { get; set; }
        public string CompletedIndicator { get; set; }
        public string RemAttachedIndicator { get; set; }
        public Nullable<int> BillAccountId { get; set; }
        public Nullable<System.DateTime> VisitNoteDateTime { get; set; }
        public Nullable<System.DateTime> SignedDateTime { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public Nullable<int> DocumentSer { get; set; }
        public string TemplateName { get; set; }
        public string ImgDocumentId { get; set; }
        public string EnteredByUser { get; set; }
        public Nullable<System.DateTime> EnteredDateTime { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
