//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cube_FactDVH
    {
        public long FactDVHID { get; set; }
        public double DoseValue { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimPlanID { get; set; }
        public Nullable<long> DimStructureID { get; set; }
        public Nullable<long> DimCourseID { get; set; }
        public Nullable<long> ctrPlanSer { get; set; }
        public Nullable<long> ctrCourseSer { get; set; }
        public Nullable<long> ctrPatientSer { get; set; }
        public Nullable<long> ctrStructureSer { get; set; }
        public Nullable<long> ctrStructureSetSer { get; set; }
        public string MaxDoseUnit { get; set; }
        public string MinDoseUnit { get; set; }
        public Nullable<decimal> MaxDose { get; set; }
        public Nullable<decimal> MinDose { get; set; }
        public Nullable<double> Coverage { get; set; }
        public Nullable<double> SamplingCoverage { get; set; }
        public Nullable<decimal> StdDev { get; set; }
        public Nullable<double> DataArrayVolume { get; set; }
        public Nullable<double> RelativeDose { get; set; }
        public Nullable<double> RelativeVolume { get; set; }
        public string Structure { get; set; }
        public string StructureDicomType { get; set; }
        public string GenerationAlgorithm { get; set; }
        public Nullable<double> MaterialCTValue { get; set; }
        public Nullable<double> TCPAlpha { get; set; }
        public string SubType { get; set; }
        public Nullable<double> TCPBeta { get; set; }
        public Nullable<double> TCPGamma { get; set; }
        public Nullable<System.DateTime> FirstDayOfTreatment { get; set; }
        public Nullable<System.DateTime> LastDayOfTreatment { get; set; }
        public string PlanSetupName { get; set; }
        public string TreatmentTechnique { get; set; }
        public string VolumeId { get; set; }
        public Nullable<double> PrimaryRefPointDeliveredSum { get; set; }
        public string IMRTOrRapidArc { get; set; }
        public Nullable<double> PrimaryRefPointRemainingSum { get; set; }
        public Nullable<double> PrimaryRefPointPlannedSum { get; set; }
    }
}
