//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cube_FactActivity
    {
        public long DimActivityTransactionID { get; set; }
        public Nullable<long> DimActivityID { get; set; }
        public Nullable<long> DimResourceID { get; set; }
        public Nullable<long> DimUserID_ActivityCreatedBy { get; set; }
        public Nullable<long> DimDateID_ScheduledEndTime { get; set; }
        public Nullable<long> DimDateID_AppointmentDateTime { get; set; }
        public Nullable<long> DimDateID_ActivityStartDateTime { get; set; }
        public Nullable<long> DimDateID_ActivityEndDateTime { get; set; }
        public Nullable<long> DimDateID_PatientArrivalDateTime { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<System.DateTime> ScheduledEndTime { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public string AppointmentStatus { get; set; }
        public string IsScheduled { get; set; }
        public Nullable<System.DateTime> ActivityStartDateTime { get; set; }
        public Nullable<System.DateTime> ActivityEndDateTime { get; set; }
        public string ActivityPriority { get; set; }
        public string ActivityNote { get; set; }
        public string CheckedIn { get; set; }
        public Nullable<System.DateTime> PatientArrivalDateTime { get; set; }
        public string ActualResourceType { get; set; }
        public string PatientLocation { get; set; }
        public Nullable<int> WaitListedFlag { get; set; }
        public Nullable<long> ctrScheduledActivitySer { get; set; }
        public Nullable<long> ctrActivityInstanceSer { get; set; }
        public Nullable<long> ctrActivitySer { get; set; }
        public Nullable<long> ctrActivityCategorySer { get; set; }
        public Nullable<long> ctrResourceSer { get; set; }
        public Nullable<long> ctrCreatedByResourceSer { get; set; }
        public Nullable<long> DimProcedureCodeID { get; set; }
        public Nullable<long> DimDoctorID { get; set; }
        public Nullable<long> DimDoctorID_AttendingOncologist { get; set; }
        public Nullable<int> ActivityDurationInMin { get; set; }
        public Nullable<decimal> ActivityCost { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> PrimaryGlobalCharge { get; set; }
        public Nullable<decimal> PrimaryProfessionalCharge { get; set; }
        public Nullable<decimal> PrimaryTechnicalCharge { get; set; }
        public Nullable<decimal> ActualCharge { get; set; }
        public Nullable<decimal> OtherTechnicalCharge { get; set; }
        public Nullable<decimal> OtherGlobalCharge { get; set; }
        public Nullable<decimal> OtherProfessionalCharge { get; set; }
        public Nullable<double> GlobalRVU { get; set; }
        public Nullable<double> ProfessionalRVU { get; set; }
        public Nullable<double> TechnicalRVU { get; set; }
        public Nullable<long> DimPrimaryOncologistID { get; set; }
        public Nullable<long> DimPrimaryReferringPhysicianID { get; set; }
        public Nullable<long> FactActivityBillingID { get; set; }
        public Nullable<long> ctrActInstProcCodeSer { get; set; }
    }
}
