//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cube_FactPatientLabResult
    {
        public long FactPatientLabResultID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public string UOM { get; set; }
        public string StatusType { get; set; }
        public string ComponentType { get; set; }
        public string AbnormalFlagCode { get; set; }
        public string SymbolCode { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> TestYear { get; set; }
        public Nullable<int> TestMonthNo { get; set; }
        public string TestMonth { get; set; }
        public Nullable<int> TestQuarterNo { get; set; }
        public string TestQuarter { get; set; }
        public string TypeOfTest { get; set; }
        public string ComponentName { get; set; }
        public Nullable<double> TestValue { get; set; }
        public Nullable<double> MinNorm { get; set; }
        public Nullable<double> MaxNorm { get; set; }
        public string TestValueStatusCode { get; set; }
        public string TestValueStatusDescription { get; set; }
        public Nullable<double> MinReason { get; set; }
        public Nullable<double> MaxReason { get; set; }
        public string ResultApprovedIndicator { get; set; }
        public string ProducerStakeholderId { get; set; }
        public string DspRefRange { get; set; }
        public string PatientId { get; set; }
        public Nullable<int> TestResultGroupId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> PatientVisitId { get; set; }
        public Nullable<int> TestResultId { get; set; }
    }
}
