//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cube_DimActivityTransaction
    {
        public long DimActivityTransactionID { get; set; }
        public string AppointmentStatus { get; set; }
        public string IsScheduled { get; set; }
        public string ActivityName { get; set; }
        public string ActivityCategory { get; set; }
        public Nullable<int> DefaultDuration { get; set; }
        public string ActivityType { get; set; }
        public string TaskORAppointment { get; set; }
        public Nullable<int> WaitListedFlag { get; set; }
        public string ActivityPriority { get; set; }
        public string CheckedIn { get; set; }
        public string PatientLocation { get; set; }
        public Nullable<int> ScheduledStartYear { get; set; }
        public Nullable<int> ScheduledStartMonthNo { get; set; }
        public string ScheduledStartMonth { get; set; }
        public Nullable<int> ScheduledStartQuarterNo { get; set; }
        public string ScheduledStartQuarter { get; set; }
        public Nullable<System.DateTime> ScheduledStartDate { get; set; }
        public Nullable<int> ActivityStartYear { get; set; }
        public Nullable<int> ActivityStartMonthNo { get; set; }
        public string ActivityStartMonth { get; set; }
        public Nullable<int> ActivityStartQuarterNo { get; set; }
        public string ActivityStartQuarter { get; set; }
        public Nullable<System.DateTime> ActivityStartDate { get; set; }
        public string ActivityStartMonthName { get; set; }
        public string ActivityEndMonthName { get; set; }
        public Nullable<int> ActivityEndYear { get; set; }
        public Nullable<int> ActivityEndMonthNo { get; set; }
        public string ActivityEndMonth { get; set; }
        public Nullable<int> ActivityEndQuarterNo { get; set; }
        public string ActivityEndQuarter { get; set; }
        public Nullable<System.DateTime> ActivityEndDate { get; set; }
        public Nullable<int> ScheduledEndYear { get; set; }
        public Nullable<int> ScheduledEndMonthNo { get; set; }
        public string ScheduledEndMonth { get; set; }
        public Nullable<int> ScheduledEndQuarterNo { get; set; }
        public string ScheduledEndQuarter { get; set; }
        public Nullable<System.DateTime> ScheduledEndDate { get; set; }
        public Nullable<int> PatientArrivalYear { get; set; }
        public Nullable<int> PatientArrivalMonthNo { get; set; }
        public string PatientArrivalMonth { get; set; }
        public Nullable<int> PatientArrivalQuaretrNo { get; set; }
        public string PatientArrivalQuarter { get; set; }
        public Nullable<System.DateTime> PatientArrivalDate { get; set; }
        public Nullable<int> ActualActivityDuration { get; set; }
        public Nullable<System.DateTime> FromDateOfService { get; set; }
        public Nullable<int> FromDateOfServiceMonthNo { get; set; }
        public string FromDateOfServiceMonth { get; set; }
        public string FromDateOfServiceQuarterName { get; set; }
        public Nullable<int> FromDateOfServiceQuarterNo { get; set; }
        public Nullable<int> FromDateOfServiceYear { get; set; }
        public string FromDateOfServiceMonthName { get; set; }
        public Nullable<System.DateTime> ToDateOfService { get; set; }
        public Nullable<int> ToDateOfServiceMonthNo { get; set; }
        public string ToDateOfServiceMonth { get; set; }
        public string ToDateOfServiceQuarterName { get; set; }
        public Nullable<int> ToDateOfServiceQuarterNo { get; set; }
        public Nullable<int> ToDateOfServiceYear { get; set; }
        public string ToDateOfServiceMonthName { get; set; }
        public Nullable<System.DateTime> MarkedCompletedDate { get; set; }
        public Nullable<int> MarkedCompletedMonthNo { get; set; }
        public string MarkedCompletedMonth { get; set; }
        public string MarkedCompletedQuarterName { get; set; }
        public Nullable<int> MarkedCompletedQuarterNo { get; set; }
        public Nullable<int> MarkedCompletedYear { get; set; }
        public string MarkedCompletedMonthName { get; set; }
        public Nullable<System.DateTime> ExportedDate { get; set; }
        public Nullable<int> ExportedMonthNo { get; set; }
        public string ExportedMonth { get; set; }
        public string ExportedQuarterName { get; set; }
        public Nullable<int> ExportedQuarterNo { get; set; }
        public Nullable<int> ExportedYear { get; set; }
        public string ExportedMonthName { get; set; }
        public Nullable<System.DateTime> CreditedDate { get; set; }
        public string ActivityObjectStatus { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CompletedMonthNo { get; set; }
        public string CompletedMonth { get; set; }
        public string CompletedQuarterName { get; set; }
        public Nullable<int> CompletedQuarterNo { get; set; }
        public Nullable<int> CompletedYear { get; set; }
        public string CompletedMonthName { get; set; }
        public string CompletedByUserFirstName { get; set; }
        public string CompletedByUserLastName { get; set; }
        public string CompletedByUserFullName { get; set; }
        public string CompletedByUserDisplayName { get; set; }
    }
}
