//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomGrouping
    {
        public long CustomGroupingID { get; set; }
        public string ColumnToMap { get; set; }
        public string GroupLevel1 { get; set; }
        public string GroupLevel2 { get; set; }
        public string GroupLevel3 { get; set; }
        public string GroupLevel4 { get; set; }
        public string GroupLevel5 { get; set; }
    }
}
