//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomGroup
    {
        public long CustomGroupID { get; set; }
        public string CustomGroupName { get; set; }
        public Nullable<int> HierarchyLevel { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> LogID { get; set; }
    }
}
