//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimActivityTransactionWorkTable
    {
        public long DimActivityTransactionID { get; set; }
        public string DxSite_DerivedAppointmentTaskDate { get; set; }
        public string NewDxSite_DerivedAppointmentTaskDate { get; set; }
    }
}
