//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimActivityTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimActivityTransaction()
        {
            this.DimRxes = new HashSet<DimRx>();
            this.DimPatientDiseaseResponses = new HashSet<DimPatientDiseaseResponse>();
            this.DimPatientVisitTrackings = new HashSet<DimPatientVisitTracking>();
            this.DimVisitEventDetails = new HashSet<DimVisitEventDetail>();
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
            this.FactActivityDiagnosis = new HashSet<FactActivityDiagnosi>();
            this.FactPatientExams = new HashSet<FactPatientExam>();
            this.FactPatientLabResults = new HashSet<FactPatientLabResult>();
            this.FactPatientToxicities = new HashSet<FactPatientToxicity>();
            this.FactPhysicianOrders = new HashSet<FactPhysicianOrder>();
            this.FactQuestionnaires = new HashSet<FactQuestionnaire>();
        }
    
        public long DimActivityTransactionID { get; set; }
        public Nullable<long> DimActivityID { get; set; }
        public Nullable<long> DimResourceID { get; set; }
        public Nullable<long> DimLookupID_AppointmentStatus { get; set; }
        public Nullable<long> DimLookupID_ActualResourceType { get; set; }
        public Nullable<long> DimUserID_ActivityCreatedBy { get; set; }
        public Nullable<long> DimDateID_ScheduledEndTime { get; set; }
        public Nullable<long> DimDateID_AppointmentDateTime { get; set; }
        public Nullable<long> DimDateID_ActivityStartDateTime { get; set; }
        public Nullable<long> DimDateID_ActivityEndDateTime { get; set; }
        public Nullable<long> DimDateID_PatientArrivalDateTime { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<System.DateTime> ScheduledEndTime { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public string IsScheduled { get; set; }
        public Nullable<System.DateTime> ActivityStartDateTime { get; set; }
        public Nullable<System.DateTime> ActivityEndDateTime { get; set; }
        public string ActivityPriority { get; set; }
        public string ActivityNote { get; set; }
        public string CheckedIn { get; set; }
        public Nullable<System.DateTime> PatientArrivalDateTime { get; set; }
        public string PatientLocation { get; set; }
        public Nullable<int> WaitListedFlag { get; set; }
        public Nullable<long> ctrScheduledActivitySer { get; set; }
        public Nullable<long> ctrActivityInstanceSer { get; set; }
        public Nullable<long> ctrActivitySer { get; set; }
        public Nullable<long> ctrActivityCategorySer { get; set; }
        public Nullable<long> ctrResourceSer { get; set; }
        public Nullable<long> ctrCreatedByResourceSer { get; set; }
        public Nullable<int> ActivityInstanceRevCount { get; set; }
        public string AppointmentStatus { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<long> DimDateID_CreationDate { get; set; }
        public Nullable<int> AppointmentInstanceFlag { get; set; }
        public string MOROIndicator { get; set; }
        public Nullable<long> DimMOTreatmentPlanID { get; set; }
        public Nullable<long> DimClinicID { get; set; }
        public Nullable<long> DimLookupID_CancelReasonType { get; set; }
        public Nullable<int> VisitCycleNumber { get; set; }
        public Nullable<int> VisitCycleDay { get; set; }
        public Nullable<int> ctrpt_visit_id { get; set; }
        public Nullable<long> DimMedoncPlanID { get; set; }
        public Nullable<long> DimMedoncPlanPhaseID { get; set; }
        public Nullable<System.DateTime> DerivedAppointmentTaskDate { get; set; }
        public Nullable<long> DimLookupID_AppointmentResourceStatus { get; set; }
        public string AppointmentResourceStatus { get; set; }
        public string DxSite_DerivedAppointmentTaskDate { get; set; }
        public Nullable<int> ActivityOwnerFlag { get; set; }
        public Nullable<double> AppointmentDateTimeFloatValue { get; set; }
    
        public virtual DimActivity DimActivity { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimResource DimResource { get; set; }
        public virtual DimUser DimUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimRx> DimRxes { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimDate DimDate3 { get; set; }
        public virtual DimDate DimDate4 { get; set; }
        public virtual DimDate DimDate5 { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        public virtual DimMedoncPlan DimMedoncPlan { get; set; }
        public virtual DimMedoncPlanPhase DimMedoncPlanPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientDiseaseResponse> DimPatientDiseaseResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientVisitTracking> DimPatientVisitTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimVisitEventDetail> DimVisitEventDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityDiagnosi> FactActivityDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientExam> FactPatientExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPhysicianOrder> FactPhysicianOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires { get; set; }
    }
}
