//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimAddOn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimAddOn()
        {
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories1 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories2 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories3 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories4 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories5 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories6 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories7 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories8 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories9 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories10 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories11 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories12 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories13 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories14 = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimAddOnID { get; set; }
        public Nullable<long> DimMachineID { get; set; }
        public string AddOnId { get; set; }
        public string AddOnName { get; set; }
        public string AddOnType { get; set; }
        public string AddOnSubType { get; set; }
        public Nullable<long> AddOnSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimMachine DimMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories14 { get; set; }
    }
}
