//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimActivityAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimActivityAttribute()
        {
            this.FactActivityCaptureAttributes = new HashSet<FactActivityCaptureAttribute>();
        }
    
        public long DimActivityAttributeID { get; set; }
        public Nullable<long> DimActivityID { get; set; }
        public string UserDefActAttrId { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserDefActAttrRevCount { get; set; }
        public Nullable<long> ctrUserDefActAttrSer { get; set; }
        public Nullable<long> ctrActivityAttributeSer { get; set; }
        public Nullable<int> ActivityAttributeRevCount { get; set; }
        public string ActivityAttributeObjectStatus { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimActivity DimActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityCaptureAttribute> FactActivityCaptureAttributes { get; set; }
    }
}
