//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimCellType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimCellType()
        {
            this.FactPatientDiagnosis = new HashSet<FactPatientDiagnosi>();
        }
    
        public long DimCellTypeID { get; set; }
        public string CellTypeBehaviorCode { get; set; }
        public Nullable<int> ClsSchemeId { get; set; }
        public string MorphCode { get; set; }
        public Nullable<int> MorphCodeSequence { get; set; }
        public string VarisHistologyCode { get; set; }
        public string CellTypeENU { get; set; }
        public string CellTypeFRA { get; set; }
        public string CellTypeESN { get; set; }
        public string CellTypeCHS { get; set; }
        public string CellTypeDEU { get; set; }
        public string CellTypeITA { get; set; }
        public string CellTypeJPN { get; set; }
        public string CellTypePTB { get; set; }
        public string CellTypeSVE { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis { get; set; }
    }
}
