//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimCourse()
        {
            this.DimFields = new HashSet<DimField>();
            this.DimPlans = new HashSet<DimPlan>();
            this.DimTreatmentTransactions = new HashSet<DimTreatmentTransaction>();
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
            this.FactCourseDiagnosis = new HashSet<FactCourseDiagnosi>();
            this.FactDVHs = new HashSet<FactDVH>();
            this.FactPatientImages = new HashSet<FactPatientImage>();
            this.FactPatientPrescriptions = new HashSet<FactPatientPrescription>();
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimCourseID { get; set; }
        public long DimPatientID { get; set; }
        public string CourseId { get; set; }
        public Nullable<System.DateTime> CourseStartDateTime { get; set; }
        public Nullable<int> NoTxSessionPlanned { get; set; }
        public Nullable<int> NoTxSessionDelivered { get; set; }
        public Nullable<int> NoTxSessionRemaining { get; set; }
        public Nullable<double> DoseDelivered { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public string Comment { get; set; }
        public Nullable<long> ctrCourseSer { get; set; }
        public Nullable<long> DimLookupID_ClinicalStatus { get; set; }
        public Nullable<long> DimLookupID_TreatmentIntentType { get; set; }
        public Nullable<long> DimDxSiteID { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimDxSite DimDxSite { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimField> DimFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPlan> DimPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimTreatmentTransaction> DimTreatmentTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactCourseDiagnosi> FactCourseDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactDVH> FactDVHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientImage> FactPatientImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientPrescription> FactPatientPrescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
    }
}
