//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDate()
        {
            this.DimActivityTransactions = new HashSet<DimActivityTransaction>();
            this.DimActivityTransactions1 = new HashSet<DimActivityTransaction>();
            this.DimActivityTransactions2 = new HashSet<DimActivityTransaction>();
            this.DimActivityTransactions3 = new HashSet<DimActivityTransaction>();
            this.DimActivityTransactions4 = new HashSet<DimActivityTransaction>();
            this.DimActivityTransactions5 = new HashSet<DimActivityTransaction>();
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
            this.FactActivityBillings1 = new HashSet<FactActivityBilling>();
            this.FactActivityBillings2 = new HashSet<FactActivityBilling>();
            this.FactActivityBillings3 = new HashSet<FactActivityBilling>();
            this.FactActivityBillings4 = new HashSet<FactActivityBilling>();
            this.FactActivityBillings5 = new HashSet<FactActivityBilling>();
            this.FactActivityBillings6 = new HashSet<FactActivityBilling>();
            this.FactActivityBillings7 = new HashSet<FactActivityBilling>();
            this.FactInVivoDosimetries = new HashSet<FactInVivoDosimetry>();
            this.FactInVivoDosimetries1 = new HashSet<FactInVivoDosimetry>();
            this.FactPatients = new HashSet<FactPatient>();
            this.FactPatients1 = new HashSet<FactPatient>();
            this.FactPatients2 = new HashSet<FactPatient>();
            this.FactPatientAllergies = new HashSet<FactPatientAllergy>();
            this.FactPatientDiagnosis = new HashSet<FactPatientDiagnosi>();
            this.FactPatientExams = new HashSet<FactPatientExam>();
            this.FactPatientExams1 = new HashSet<FactPatientExam>();
            this.FactPatientExams2 = new HashSet<FactPatientExam>();
            this.FactPatientFamilyHistories = new HashSet<FactPatientFamilyHistory>();
            this.FactPatientImages = new HashSet<FactPatientImage>();
            this.FactPatientImages1 = new HashSet<FactPatientImage>();
            this.FactPatientLabResults = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults1 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults2 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults3 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults4 = new HashSet<FactPatientLabResult>();
            this.FactPatientMedicalHistories = new HashSet<FactPatientMedicalHistory>();
            this.FactPatientMedicalHistories1 = new HashSet<FactPatientMedicalHistory>();
            this.FactPatientMedicalHistories2 = new HashSet<FactPatientMedicalHistory>();
            this.FactPatientToxicities = new HashSet<FactPatientToxicity>();
            this.FactPatientToxicities1 = new HashSet<FactPatientToxicity>();
            this.FactPatientToxicities2 = new HashSet<FactPatientToxicity>();
            this.FactPatientToxicities3 = new HashSet<FactPatientToxicity>();
            this.FactPatientToxicities4 = new HashSet<FactPatientToxicity>();
            this.FactPatientToxicities5 = new HashSet<FactPatientToxicity>();
            this.FactPhysicianOrders = new HashSet<FactPhysicianOrder>();
            this.FactPhysicianOrders1 = new HashSet<FactPhysicianOrder>();
            this.FactPhysicianOrders2 = new HashSet<FactPhysicianOrder>();
            this.FactQuestionnaires = new HashSet<FactQuestionnaire>();
            this.FactQuestionnaires1 = new HashSet<FactQuestionnaire>();
            this.FactQuestionnaires2 = new HashSet<FactQuestionnaire>();
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories1 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories2 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories3 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories4 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories5 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories6 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories7 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories8 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories9 = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimDateID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DateValueInt { get; set; }
        public string FullDateDesc { get; set; }
        public Nullable<int> CalMonthNo { get; set; }
        public Nullable<int> CalQuarterNo { get; set; }
        public Nullable<int> CalHalfYearNo { get; set; }
        public Nullable<int> CalYearNo { get; set; }
        public string CalMonthName { get; set; }
        public Nullable<System.DateTime> CalMonthFirstDate { get; set; }
        public Nullable<System.DateTime> CalMonthLastDate { get; set; }
        public Nullable<int> DaysInCalMonth { get; set; }
        public string CalQuarterName { get; set; }
        public Nullable<System.DateTime> CalQuarterFirstDate { get; set; }
        public Nullable<System.DateTime> CalQuarterLastDate { get; set; }
        public Nullable<int> DaysInCalQuarter { get; set; }
        public string CalHalfYearName { get; set; }
        public Nullable<System.DateTime> CalHalfYearFirstDate { get; set; }
        public Nullable<System.DateTime> CalHalfYearLastDate { get; set; }
        public Nullable<int> DaysInCalHalfYear { get; set; }
        public Nullable<System.DateTime> CalYearFirstDate { get; set; }
        public Nullable<System.DateTime> CalYearLastDate { get; set; }
        public Nullable<int> DaysInCalYear { get; set; }
        public string CalYYYYMM { get; set; }
        public string CalYYYYQuarter { get; set; }
        public string CalYYYYHalfYear { get; set; }
        public string CalYYYY { get; set; }
        public Nullable<int> LastDayInWeekIndicator { get; set; }
        public Nullable<int> LastDayInMonthIndicator { get; set; }
        public Nullable<int> LastDayInQuarterIndicator { get; set; }
        public Nullable<int> LastDayInHalfYearIndicator { get; set; }
        public Nullable<int> LastDayInYearIndicator { get; set; }
        public Nullable<int> HoliDayIndicator { get; set; }
        public string CalMonthYear { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> MonthNum { get; set; }
        public Nullable<int> MonthWeekNo { get; set; }
        public string YearWeekName { get; set; }
        public string MonthWeekName { get; set; }
        public Nullable<int> YearWeekNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactInVivoDosimetry> FactInVivoDosimetries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactInVivoDosimetry> FactInVivoDosimetries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientAllergy> FactPatientAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientExam> FactPatientExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientExam> FactPatientExams1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientExam> FactPatientExams2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientFamilyHistory> FactPatientFamilyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientImage> FactPatientImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientImage> FactPatientImages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedicalHistory> FactPatientMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedicalHistory> FactPatientMedicalHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedicalHistory> FactPatientMedicalHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPhysicianOrder> FactPhysicianOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPhysicianOrder> FactPhysicianOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPhysicianOrder> FactPhysicianOrders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories9 { get; set; }
    }
}
