//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDxSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDxSite()
        {
            this.DimCourses = new HashSet<DimCourse>();
            this.FactActivityDiagnosis = new HashSet<FactActivityDiagnosi>();
            this.FactActivityDiagnosis1 = new HashSet<FactActivityDiagnosi>();
            this.FactCourseDiagnosis = new HashSet<FactCourseDiagnosi>();
            this.FactCourseDiagnosis1 = new HashSet<FactCourseDiagnosi>();
            this.FactPatientDiagnosis = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis1 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis2 = new HashSet<FactPatientDiagnosi>();
        }
    
        public long DimDxSiteID { get; set; }
        public Nullable<int> TpClsTypeId { get; set; }
        public Nullable<int> TpClsValueId { get; set; }
        public string SiteDescENU { get; set; }
        public string SiteDescFRA { get; set; }
        public string SiteDescESN { get; set; }
        public string SiteDescCHS { get; set; }
        public string SiteDescDEU { get; set; }
        public string SiteDescITA { get; set; }
        public string SiteDescJPN { get; set; }
        public string SiteDescPTB { get; set; }
        public string SiteDescSVE { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimCourse> DimCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityDiagnosi> FactActivityDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityDiagnosi> FactActivityDiagnosis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactCourseDiagnosi> FactCourseDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactCourseDiagnosi> FactCourseDiagnosis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis2 { get; set; }
    }
}
