//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimEnergy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimEnergy()
        {
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories1 = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimEnergyID { get; set; }
        public Nullable<long> DimMachineID { get; set; }
        public string RadiationType { get; set; }
        public Nullable<int> Energy { get; set; }
        public Nullable<int> MaxEnergy { get; set; }
        public Nullable<int> MinDoseRate { get; set; }
        public Nullable<int> MaxDoseRate { get; set; }
        public Nullable<long> ctrEnergyModeSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimMachine DimMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories1 { get; set; }
    }
}
