//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimField()
        {
            this.DimTreatmentTransactions = new HashSet<DimTreatmentTransaction>();
            this.FactPatientImages = new HashSet<FactPatientImage>();
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimFieldID { get; set; }
        public Nullable<long> DimPlanID { get; set; }
        public Nullable<long> DimCourseID { get; set; }
        public string RadiationId { get; set; }
        public string RadiationName { get; set; }
        public Nullable<double> CollimatorX1 { get; set; }
        public Nullable<double> CollimatorX2 { get; set; }
        public Nullable<double> CollimatorY1 { get; set; }
        public Nullable<double> CollimatorY2 { get; set; }
        public Nullable<double> CouchLat { get; set; }
        public Nullable<double> CouchLng { get; set; }
        public Nullable<double> CouchVrt { get; set; }
        public string GantryRtnDirection { get; set; }
        public string GantryRtnExt { get; set; }
        public Nullable<double> GantryRotation { get; set; }
        public Nullable<double> IsoCenterPositionX { get; set; }
        public Nullable<double> IsoCenterPositionY { get; set; }
        public Nullable<double> IsoCenterPositionZ { get; set; }
        public Nullable<double> StopAngle { get; set; }
        public Nullable<double> FixLightAzimuthAngle { get; set; }
        public Nullable<double> PatientSupportAngle { get; set; }
        public Nullable<int> GatingFlag { get; set; }
        public Nullable<int> SetupFieldFlag { get; set; }
        public Nullable<System.DateTime> LastTreatmentDate { get; set; }
        public string PrimaryDosimeterUnit { get; set; }
        public string SetupNote { get; set; }
        public Nullable<double> SSD { get; set; }
        public Nullable<double> MURounded { get; set; }
        public string ToleranceId { get; set; }
        public string ToleranceTable { get; set; }
        public Nullable<double> FixLightPolarPos { get; set; }
        public Nullable<double> WedgeDose { get; set; }
        public Nullable<double> RefDose { get; set; }
        public string HstryUserName { get; set; }
        public Nullable<System.DateTime> HstryDateTime { get; set; }
        public string CollMode { get; set; }
        public Nullable<double> CollRtn { get; set; }
        public Nullable<double> PlannedTreatmentTime { get; set; }
        public string MLCPlanType { get; set; }
        public string IndexParameterType { get; set; }
        public string IMRTOrRapidArc { get; set; }
        public Nullable<long> ctrRadiationSer { get; set; }
        public Nullable<long> ctrToleranceSer { get; set; }
        public Nullable<long> ctrRefImageSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimCourse DimCourse { get; set; }
        public virtual DimPlan DimPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimTreatmentTransaction> DimTreatmentTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientImage> FactPatientImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
    }
}
