//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimHospitalDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimHospitalDepartment()
        {
            this.DimActivityTransactions = new HashSet<DimActivityTransaction>();
            this.DimClinics = new HashSet<DimClinic>();
            this.DimPatientDepartments = new HashSet<DimPatientDepartment>();
            this.DimPatientDepartmentbyCUIDs = new HashSet<DimPatientDepartmentbyCUID>();
            this.DimUserDepartments = new HashSet<DimUserDepartment>();
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
            this.DimInstituteLocations = new HashSet<DimInstituteLocation>();
            this.DimPatientJournals = new HashSet<DimPatientJournal>();
            this.DimPatientVisitTrackings = new HashSet<DimPatientVisitTracking>();
            this.DimPayors = new HashSet<DimPayor>();
            this.DimVisitEventDetails = new HashSet<DimVisitEventDetail>();
            this.FactPatients = new HashSet<FactPatient>();
            this.FactPatientLabResults = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults1 = new HashSet<FactPatientLabResult>();
            this.FactPatientMedoncTreatments = new HashSet<FactPatientMedoncTreatment>();
            this.FactPhysicianOrders = new HashSet<FactPhysicianOrder>();
            this.FactQuestionnaires = new HashSet<FactQuestionnaire>();
        }
    
        public long DimHospitalDepartmentID { get; set; }
        public string HospitalName { get; set; }
        public string HospitalLocation { get; set; }
        public string HospitalCompleteAddress { get; set; }
        public string HospitalWebAddress { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentComment { get; set; }
        public Nullable<System.DateTime> DepartmentHstryDateTime { get; set; }
        public string DepartmentHstryUserName { get; set; }
        public Nullable<System.DateTime> HospitalHstryDateTime { get; set; }
        public string HospitalHstryUserName { get; set; }
        public Nullable<long> ctrHospitalSer { get; set; }
        public Nullable<long> ctrDepartmentSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public string ctrinst_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimClinic> DimClinics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientDepartment> DimPatientDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientDepartmentbyCUID> DimPatientDepartmentbyCUIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimUserDepartment> DimUserDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimInstituteLocation> DimInstituteLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientJournal> DimPatientJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientVisitTracking> DimPatientVisitTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPayor> DimPayors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimVisitEventDetail> DimVisitEventDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedoncTreatment> FactPatientMedoncTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPhysicianOrder> FactPhysicianOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires { get; set; }
    }
}
