//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimInSightiveActivityTransactionWorkTable
    {
        public int ID { get; set; }
        public long DimActivityTransactionID { get; set; }
        public string DepartmentName { get; set; }
        public string HospitalName { get; set; }
        public long DimPatientID { get; set; }
        public string PatientId { get; set; }
        public string ActivityCategoryCode { get; set; }
        public string ActivityCode { get; set; }
        public string IsScheduled { get; set; }
        public long DimActivityID { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public Nullable<System.DateTime> ActivityStartDateTime { get; set; }
        public string DxSite_DerivedAppointmentTaskDate { get; set; }
        public string AppointmentStatus { get; set; }
        public string ActivityObjectStatus { get; set; }
        public Nullable<long> DimResourceID { get; set; }
        public string DoctorFullName { get; set; }
        public Nullable<byte> isIgnore { get; set; }
        public Nullable<short> ActivityOrder { get; set; }
        public Nullable<bool> isFirstEntry { get; set; }
        public Nullable<bool> isLastEntry { get; set; }
    }
}
