//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimInstituteLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimInstituteLocation()
        {
            this.DimVisitEventDetails = new HashSet<DimVisitEventDetail>();
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
        }
    
        public long DimInstituteLocationID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public string EventType { get; set; }
        public string LocationDescription { get; set; }
        public string BuildingName { get; set; }
        public string FloorName { get; set; }
        public string RoomName { get; set; }
        public string DepartmentName { get; set; }
        public string LocationGroupName { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> SlotSize { get; set; }
        public string LocationOpenTime { get; set; }
        public string LocationCloseTime { get; set; }
        public string LocationComment { get; set; }
        public string LocationTel { get; set; }
        public string PrimaryInd { get; set; }
        public string ActiveEntryInd { get; set; }
        public Nullable<int> ctrloc_id { get; set; }
        public Nullable<int> ctrbldg_id { get; set; }
        public Nullable<int> ctrfloor_id { get; set; }
        public Nullable<int> ctrroom_id { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimVisitEventDetail> DimVisitEventDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
    }
}
