//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimICDOSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimICDOSite()
        {
            this.FactPatientDiagnosis = new HashSet<FactPatientDiagnosi>();
        }
    
        public long DimICDOSiteID { get; set; }
        public string ICDOSiteCodeId { get; set; }
        public Nullable<int> ICDOSequence { get; set; }
        public Nullable<int> ICDOClsSchemeId { get; set; }
        public string ICDOSiteCodeENU { get; set; }
        public string ICDOSiteCodeFRA { get; set; }
        public string ICDOSiteCodeESN { get; set; }
        public string ICDOSiteCodeCHS { get; set; }
        public string ICDOSiteCodeDEU { get; set; }
        public string ICDOSiteCodeITA { get; set; }
        public string ICDOSiteCodeJPN { get; set; }
        public string ICDOSiteCodePTB { get; set; }
        public string ICDOSiteCodeSVE { get; set; }
        public string ICDOVersionENU { get; set; }
        public string ICDOVersionFRA { get; set; }
        public string ICDOVersionESN { get; set; }
        public string ICDOVersionCHS { get; set; }
        public string ICDOVersionDEU { get; set; }
        public string ICDOVersionITA { get; set; }
        public string ICDOVersionJPN { get; set; }
        public string ICDOVersionPTB { get; set; }
        public string ICDOVersionSVE { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis { get; set; }
    }
}
