//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimLookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimLookup()
        {
            this.DimActivityTransactions = new HashSet<DimActivityTransaction>();
            this.DimActivityTransactions1 = new HashSet<DimActivityTransaction>();
            this.DimConstantResources = new HashSet<DimConstantResource>();
            this.DimDoctors = new HashSet<DimDoctor>();
            this.DimResources = new HashSet<DimResource>();
            this.FactPatientFamilyHistories = new HashSet<FactPatientFamilyHistory>();
            this.DimPatientUserDefinedLabels = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels1 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels2 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels3 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels4 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels5 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels6 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels7 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels8 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels9 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels10 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels11 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels12 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels13 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels14 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientUserDefinedLabels15 = new HashSet<DimPatientUserDefinedLabel>();
            this.DimQuestionnaires = new HashSet<DimQuestionnaire>();
            this.DimQuestionnaires1 = new HashSet<DimQuestionnaire>();
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
            this.FactActivityBillings1 = new HashSet<FactActivityBilling>();
            this.FactActivityBillings2 = new HashSet<FactActivityBilling>();
            this.FactPatients = new HashSet<FactPatient>();
            this.FactPatients1 = new HashSet<FactPatient>();
            this.FactPatients2 = new HashSet<FactPatient>();
            this.FactPatientAllergies = new HashSet<FactPatientAllergy>();
            this.FactPatientAllergies1 = new HashSet<FactPatientAllergy>();
            this.FactPatientDiagnosis = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis1 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis2 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis3 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis4 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis5 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis6 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis7 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis8 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis9 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis10 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis11 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis12 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis13 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis14 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis15 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis16 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis17 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis18 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis19 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientDiagnosis20 = new HashSet<FactPatientDiagnosi>();
            this.FactPatientLabResults = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults1 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults2 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults3 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults4 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults5 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults6 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults7 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults8 = new HashSet<FactPatientLabResult>();
            this.FactPatientLabResults9 = new HashSet<FactPatientLabResult>();
            this.FactPatientMedicalHistories = new HashSet<FactPatientMedicalHistory>();
            this.FactPatientToxicities = new HashSet<FactPatientToxicity>();
            this.FactPatientToxicities1 = new HashSet<FactPatientToxicity>();
            this.FactPatientToxicities2 = new HashSet<FactPatientToxicity>();
            this.FactRxDispSyringes = new HashSet<FactRxDispSyringe>();
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories1 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories2 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories3 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories4 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories5 = new HashSet<FactTreatmentHistory>();
            this.FactTreatmentHistories6 = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimLookupID { get; set; }
        public string TableName { get; set; }
        public string LookupCode { get; set; }
        public Nullable<int> LookupType { get; set; }
        public Nullable<long> SubSelector { get; set; }
        public string LookupDescriptionENU { get; set; }
        public string LookupDescriptionFRA { get; set; }
        public string LookupDescriptionESN { get; set; }
        public string LookupDescriptionCHS { get; set; }
        public string LookupDescriptionDEU { get; set; }
        public string LookupDescriptionITA { get; set; }
        public string LookupDescriptionJPN { get; set; }
        public string LookupDescriptionPTB { get; set; }
        public string LookupDescriptionSVE { get; set; }
        public Nullable<long> ctrLookupTableSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimConstantResource> DimConstantResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimDoctor> DimDoctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimResource> DimResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientFamilyHistory> FactPatientFamilyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimQuestionnaire> DimQuestionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimQuestionnaire> DimQuestionnaires1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientAllergy> FactPatientAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientAllergy> FactPatientAllergies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedicalHistory> FactPatientMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactRxDispSyringe> FactRxDispSyringes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories6 { get; set; }
    }
}
