//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMedoncPlanPhase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimMedoncPlanPhase()
        {
            this.DimActivityTransactions = new HashSet<DimActivityTransaction>();
            this.DimMedoncPlanIntervals = new HashSet<DimMedoncPlanInterval>();
            this.FactPatientMedoncTreatments = new HashSet<FactPatientMedoncTreatment>();
        }
    
        public long DimMedoncPlanPhaseID { get; set; }
        public Nullable<long> DimMedoncPlanID { get; set; }
        public Nullable<int> ctrphase_seq_no { get; set; }
        public string PhaseDescription { get; set; }
        public Nullable<int> NumberOfCycles { get; set; }
        public Nullable<int> AllowableDrift { get; set; }
        public Nullable<int> AllowableDelay { get; set; }
        public Nullable<int> TimePeriodDuration { get; set; }
        public Nullable<int> TimePeriodDurationUnit { get; set; }
        public Nullable<int> LengthOfCycle { get; set; }
        public string PhaseBriefDescription { get; set; }
        public string ConsentDescription { get; set; }
        public string RequiredIndicator { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions { get; set; }
        public virtual DimMedoncPlan DimMedoncPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimMedoncPlanInterval> DimMedoncPlanIntervals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedoncTreatment> FactPatientMedoncTreatments { get; set; }
    }
}
