//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMedoncPlanSummary
    {
        public long DimMedoncPlanSummaryID { get; set; }
        public Nullable<long> DimMedoncPlanID { get; set; }
        public string ctrtp_name { get; set; }
        public string ctrtp_vers_no { get; set; }
        public Nullable<int> ctrpln_sum_typ { get; set; }
        public string PlanSummaryTypeDescription { get; set; }
        public string PlanSummaryDescription { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimMedoncPlan DimMedoncPlan { get; set; }
    }
}
