//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMedoncPlanInterval
    {
        public long DimMedoncPlanIntervalID { get; set; }
        public Nullable<long> DimMedoncPlanID { get; set; }
        public Nullable<long> DimMedoncPlanPhaseID { get; set; }
        public Nullable<long> DimLookupID_DosageForm { get; set; }
        public Nullable<long> DimLookupID_AdminDosageUnit { get; set; }
        public string ReceipentDisciplineType { get; set; }
        public string TypeOfTest { get; set; }
        public string EventType { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public string PlanInterventionName { get; set; }
        public string InterventionDetailText { get; set; }
        public Nullable<int> PhaseSequenceNumber { get; set; }
        public Nullable<int> TPCycleNumber { get; set; }
        public Nullable<int> CycleDay { get; set; }
        public string CyclicIndicator { get; set; }
        public string PRNIndicator { get; set; }
        public string AgentName { get; set; }
        public string DoseLevelDescription { get; set; }
        public Nullable<decimal> AdminDosage { get; set; }
        public string SpecialInstructions { get; set; }
        public string ReminderShortDescription { get; set; }
        public string ReminderDescription { get; set; }
        public string ComponentName { get; set; }
        public string QuestionnaireName { get; set; }
        public Nullable<int> GradingSchemeAuthour { get; set; }
        public Nullable<System.DateTime> GradingSchemeEffectiveDate { get; set; }
        public string ToxicityType { get; set; }
        public string ToxicityComponentName { get; set; }
        public string ToxicityReason { get; set; }
        public string ToxicitySubComponentName { get; set; }
        public Nullable<int> ctrintv_id { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimMedoncPlan DimMedoncPlan { get; set; }
        public virtual DimMedoncPlanPhase DimMedoncPlanPhase { get; set; }
    }
}
