//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMedoncPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimMedoncPlan()
        {
            this.DimActivityTransactions = new HashSet<DimActivityTransaction>();
            this.DimMedoncPlanIntervals = new HashSet<DimMedoncPlanInterval>();
            this.DimMedoncPlanPhases = new HashSet<DimMedoncPlanPhase>();
            this.DimMedoncPlanSummaries = new HashSet<DimMedoncPlanSummary>();
            this.FactPatientMedoncTreatments = new HashSet<FactPatientMedoncTreatment>();
        }
    
        public long DimMedoncPlanID { get; set; }
        public string ctrtp_name { get; set; }
        public string TreatmentPlanDisplayName { get; set; }
        public string ctrtp_vers_no { get; set; }
        public string PlanStatus { get; set; }
        public string PlanStatusDesc { get; set; }
        public Nullable<int> PlanType { get; set; }
        public string PlanTypeDescription { get; set; }
        public Nullable<long> DimLookupID_Sex { get; set; }
        public Nullable<int> StartingAgeOfPatient { get; set; }
        public Nullable<int> EndingAgeOfPatient { get; set; }
        public string ClinicalTrialIndicator { get; set; }
        public string ActiveIndicator { get; set; }
        public string PlanSummary { get; set; }
        public string PlanBriefDesc { get; set; }
        public Nullable<int> PlanClassification { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimMedoncPlanInterval> DimMedoncPlanIntervals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimMedoncPlanPhase> DimMedoncPlanPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimMedoncPlanSummary> DimMedoncPlanSummaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedoncTreatment> FactPatientMedoncTreatments { get; set; }
    }
}
