//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimOperatingLimit
    {
        public long DimOperatingLimitID { get; set; }
        public Nullable<long> DimMachineID { get; set; }
        public string ParameterType { get; set; }
        public string ParameterName { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<double> DefValue { get; set; }
        public Nullable<int> LimitPrecision { get; set; }
        public Nullable<int> TolerancePossible { get; set; }
        public string MotionMode { get; set; }
        public Nullable<double> MaxSpeed { get; set; }
        public Nullable<long> ctrOperatingLimitSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimMachine DimMachine { get; set; }
    }
}
