//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPatientDiseaseResponse
    {
        public long DimPatientDiseaseResponseID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimDateID_AssessmentDate { get; set; }
        public Nullable<long> DimDateID_EffectiveDate { get; set; }
        public Nullable<int> DiseaseStatus { get; set; }
        public string DiseaseResponse { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<System.DateTime> DiseaseStatusEffectiveDate { get; set; }
        public string DiseaseStatusValidEntryIndicator { get; set; }
        public string DiagnosisValidEntryIndicator { get; set; }
        public Nullable<int> ctrpt_tx_id { get; set; }
        public Nullable<int> ctrcncr_status_id { get; set; }
        public Nullable<int> ctrDiagnosisID { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
    }
}
