//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimPlan()
        {
            this.DimFields = new HashSet<DimField>();
            this.DimTreatmentTransactions = new HashSet<DimTreatmentTransaction>();
            this.FactDVHs = new HashSet<FactDVH>();
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimPlanID { get; set; }
        public Nullable<long> DimCourseID { get; set; }
        public Nullable<long> DimLookupID_PlanStatus { get; set; }
        public string PlanUID { get; set; }
        public Nullable<int> NoFractions { get; set; }
        public Nullable<int> TreatmentOrder { get; set; }
        public string PlanSetupId { get; set; }
        public string PlanSetupName { get; set; }
        public string TreatmentOrientation { get; set; }
        public string TreatmentTechnique { get; set; }
        public string VolumeId { get; set; }
        public string PrimaryRefPointId { get; set; }
        public Nullable<double> PrimaryRefPointDelivered { get; set; }
        public Nullable<double> PrimaryRefPointPlanned { get; set; }
        public Nullable<double> PrimaryRefPointRemaining { get; set; }
        public Nullable<double> PrimaryRefPointDeliveredSum { get; set; }
        public Nullable<double> PrimaryRefPointPlannedSum { get; set; }
        public Nullable<double> PrimaryRefPointRemainingSum { get; set; }
        public Nullable<int> NoFractionsPlanned { get; set; }
        public Nullable<int> NoFractionsRemaining { get; set; }
        public Nullable<int> NoFractionsTreated { get; set; }
        public Nullable<int> NoFractionsPlannedSum { get; set; }
        public Nullable<int> NoFractionsRemainingSum { get; set; }
        public Nullable<int> NoFractionsTreatedSum { get; set; }
        public Nullable<int> NoSessionRemaining { get; set; }
        public string EnergyMode { get; set; }
        public string FractionId { get; set; }
        public Nullable<int> StartDelay { get; set; }
        public Nullable<int> FractionPatternDigitsPerDay { get; set; }
        public string FractionPattern { get; set; }
        public string PredecessorID { get; set; }
        public Nullable<int> NoSessionPlanned { get; set; }
        public string PlanComment { get; set; }
        public string PlanIntent { get; set; }
        public Nullable<int> Age { get; set; }
        public string RelationshipType { get; set; }
        public string RelatedPlanUID { get; set; }
        public string HstryUserName { get; set; }
        public Nullable<System.DateTime> HstryDateTime { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> FirstDayOfTreatment { get; set; }
        public Nullable<System.DateTime> LastDayOfTreatment { get; set; }
        public string IMRTOrRapidArc { get; set; }
        public Nullable<long> ctrPlanSetupSer { get; set; }
        public Nullable<long> ctrRTPlanSer { get; set; }
        public Nullable<long> ctrRelatedRTPlanSer { get; set; }
        public Nullable<long> ctrPlanSOPClassSer { get; set; }
        public Nullable<long> ctrRelatedPlanSOPClassSer { get; set; }
        public Nullable<long> ctrPlanRelationshipSer { get; set; }
        public Nullable<long> ctrPrimaryRefPointSer { get; set; }
        public Nullable<long> ctrFirstRTPlanSer { get; set; }
        public string RTTreatmentTechnique { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimCourse DimCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimField> DimFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimTreatmentTransaction> DimTreatmentTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactDVH> FactDVHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
    }
}
