//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPrescriptionAnatomy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimPrescriptionAnatomy()
        {
            this.FactPatientPrescriptions = new HashSet<FactPatientPrescription>();
        }
    
        public long DimPrescriptionAnatomyID { get; set; }
        public short AnatomyRole { get; set; }
        public string AnatomyName { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public string ItemType { get; set; }
        public string ItemValue { get; set; }
        public string ItemValueUnit { get; set; }
        public string Param1Value { get; set; }
        public string Param1ValueUnit { get; set; }
        public long ctrPrescriptionAnatomySer { get; set; }
        public Nullable<long> ctrPrescriptionAnatomyItemSer { get; set; }
        public long ctrPrescriptionSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientPrescription> FactPatientPrescriptions { get; set; }
    }
}
