//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPrescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimPrescription()
        {
            this.FactPatientPrescriptions = new HashSet<FactPatientPrescription>();
        }
    
        public long DimPrescriptionID { get; set; }
        public string PrescriptionName { get; set; }
        public string Status { get; set; }
        public string Revision { get; set; }
        public string Site { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationUserName { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public Nullable<int> NumberOfFractions { get; set; }
        public string Technique { get; set; }
        public string Notes { get; set; }
        public string TimeGapType { get; set; }
        public Nullable<int> PhaseGapNumberOfDays { get; set; }
        public string PhaseType { get; set; }
        public string Gating { get; set; }
        public string BolusFrequency { get; set; }
        public string BolusThickness { get; set; }
        public Nullable<int> SimulationNeeded { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public string History { get; set; }
        public string LinkedPlans { get; set; }
        public Nullable<long> RelPrescriptionSer { get; set; }
        public long ctrPrescriptionSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientPrescription> FactPatientPrescriptions { get; set; }
    }
}
