//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPayor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimPayor()
        {
            this.FactPatientPayors = new HashSet<FactPatientPayor>();
        }
    
        public long DimPayorID { get; set; }
        public string PayorCompanyName { get; set; }
        public string PayorPhone { get; set; }
        public string PayorAddress { get; set; }
        public string PayorPlanType { get; set; }
        public Nullable<System.DateTime> PayorPlanExpiraryDate { get; set; }
        public string PayorPlanNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string AuthorizedBy { get; set; }
        public string AuthorizationPhone { get; set; }
        public string AuthorizationFAX { get; set; }
        public Nullable<long> ctrPayorSer { get; set; }
        public Nullable<long> ctrPlanTypeSer { get; set; }
        public Nullable<long> ctrPayorAuthorizationSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public string InsuranceCompanyParentOrganization { get; set; }
        public string ValidEntryIndicator { get; set; }
        public Nullable<int> ctrins_co_id { get; set; }
        public Nullable<int> ctrins_co_parent_id { get; set; }
        public string MOROIndicator { get; set; }
    
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientPayor> FactPatientPayors { get; set; }
    }
}
