//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPatientPhoto
    {
        public long DimPatientPhotoID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public byte[] Picture { get; set; }
        public long ctrPatientSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimPatient DimPatient { get; set; }
    }
}
