//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPatientPerformanceStatu
    {
        public long PerformanceStatusID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimDateID_AssessmentDate { get; set; }
        public Nullable<int> PerformanceStatusScale { get; set; }
        public Nullable<long> DimDateID_PerfStatusEffectiveDate { get; set; }
        public Nullable<int> DiagnosisStatusId { get; set; }
        public Nullable<int> PerformanceStatusValue { get; set; }
        public string ImpressionDescription { get; set; }
        public string ApprovedIndicator { get; set; }
        public string PerformanceStatusDescription { get; set; }
        public string ValidEntryIndicator { get; set; }
        public string TransLogUserId { get; set; }
        public Nullable<System.DateTime> TransLogDateTime { get; set; }
        public string TransLogModifiedUserId { get; set; }
        public Nullable<System.DateTime> TransLogModifiedDateTime { get; set; }
        public string TransLogInstId { get; set; }
        public string TransLogModifiedInstId { get; set; }
        public string ClassificationValue { get; set; }
        public string ClassificationSchemeName { get; set; }
        public Nullable<int> ClassificationSchemeKey { get; set; }
        public Nullable<int> ActivityRevCount { get; set; }
        public string ApplicationCode { get; set; }
        public string ErrorReasonText { get; set; }
        public Nullable<int> ctrpt_visit_id { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> LogID { get; set; }
    }
}
