//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPrescriptionProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimPrescriptionProperty()
        {
            this.FactPatientPrescriptions = new HashSet<FactPatientPrescription>();
        }
    
        public long DimPrescriptionPropertyID { get; set; }
        public short PropertyType { get; set; }
        public string PropertyValue { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public Nullable<short> ItemType { get; set; }
        public string ItemValue { get; set; }
        public long ctrPrescriptionPropertySer { get; set; }
        public Nullable<long> ctrPrescriptionPropertyItemSer { get; set; }
        public long ctrPrescriptionSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientPrescription> FactPatientPrescriptions { get; set; }
    }
}
