//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProcedureCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimProcedureCode()
        {
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
        }
    
        public long DimProcedureCodeID { get; set; }
        public string ProcedureCode { get; set; }
        public string ProcedureCodeType { get; set; }
        public string ProcedureCodeDescription { get; set; }
        public string Description { get; set; }
        public string ProcedureBillingCode { get; set; }
        public Nullable<int> Complexity { get; set; }
        public Nullable<int> ProcedureCodeRevCount { get; set; }
        public int Exportable { get; set; }
        public Nullable<long> ctrProcedureCodeSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<System.DateTime> BillingCodeEffectiveDate { get; set; }
        public Nullable<decimal> BillingCodeEstCost { get; set; }
        public Nullable<decimal> BillingCodeBillPrice { get; set; }
        public string BillingCodeType { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<long> DimDateID_ChangeDate { get; set; }
        public string FacilityBillCode { get; set; }
        public Nullable<long> DimLookupID_ProcCodeObjectStatus { get; set; }
        public string MOROIndicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
    }
}
