//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPatientJournal
    {
        public long DimPatientJournalID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimUserID_Author { get; set; }
        public Nullable<long> DimHospitalDepartmentID_Author { get; set; }
        public Nullable<long> DimDateID_Journal { get; set; }
        public string ApprovedFlag { get; set; }
        public Nullable<System.DateTime> JournalDate { get; set; }
        public string JournalText { get; set; }
        public string JournalTypeDescription { get; set; }
        public string JournalErrorReasonText { get; set; }
        public Nullable<int> JournalRevisionNumber { get; set; }
        public string JournalValidEntryIndicator { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> ctrquick_note_id { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimUser DimUser { get; set; }
    }
}
