//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPatientVisitTracking
    {
        public long DimPatientVisitTrackingID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<System.DateTime> VisitTrackingDateTime { get; set; }
        public Nullable<int> VisitTrackingType { get; set; }
        public Nullable<int> VisitTrackingSeq { get; set; }
        public string VisitTrackingTypeDesc { get; set; }
        public string VisitTrackingAbrv { get; set; }
        public string ValidEntryInd { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> ctrpt_visit_id { get; set; }
        public Nullable<int> ctrpt_visit_tracking_id { get; set; }
        public string ctrinst_id { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimPatient DimPatient { get; set; }
    }
}
