//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPatientUserDefinedLabel
    {
        public long DimPatientUserDefinedLabelsID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimLookupID_UDFLable1 { get; set; }
        public Nullable<long> DimLookupID_UDFLable2 { get; set; }
        public Nullable<long> DimLookupID_UDFLable3 { get; set; }
        public Nullable<long> DimLookupID_UDFLable4 { get; set; }
        public Nullable<long> DimLookupID_UDFLable5 { get; set; }
        public Nullable<long> DimLookupID_UDFLable6 { get; set; }
        public Nullable<long> DimLookupID_UDFLable7 { get; set; }
        public Nullable<long> DimLookupID_UDFLable8 { get; set; }
        public Nullable<long> DimLookupID_UDFLable9 { get; set; }
        public Nullable<long> DimLookupID_UDFLable10 { get; set; }
        public Nullable<long> DimLookupID_UDFLable11 { get; set; }
        public Nullable<long> DimLookupID_UDFLable12 { get; set; }
        public Nullable<long> DimLookupID_UDFLable13 { get; set; }
        public Nullable<long> DimLookupID_UDFLable14 { get; set; }
        public Nullable<long> DimLookupID_UDFLable15 { get; set; }
        public Nullable<long> DimLookupID_UDFLable16 { get; set; }
        public string UDFValue1 { get; set; }
        public string UDFValue2 { get; set; }
        public string UDFValue3 { get; set; }
        public string UDFValue4 { get; set; }
        public string UDFValue5 { get; set; }
        public string UDFValue6 { get; set; }
        public string UDFValue7 { get; set; }
        public string UDFValue8 { get; set; }
        public string UDFValue9 { get; set; }
        public string UDFValue10 { get; set; }
        public string UDFValue11 { get; set; }
        public string UDFValue12 { get; set; }
        public string UDFValue13 { get; set; }
        public string UDFValue14 { get; set; }
        public string UDFValue15 { get; set; }
        public string UDFValue16 { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        public virtual DimLookup DimLookup2 { get; set; }
        public virtual DimLookup DimLookup3 { get; set; }
        public virtual DimLookup DimLookup4 { get; set; }
        public virtual DimLookup DimLookup5 { get; set; }
        public virtual DimLookup DimLookup6 { get; set; }
        public virtual DimLookup DimLookup7 { get; set; }
        public virtual DimLookup DimLookup8 { get; set; }
        public virtual DimLookup DimLookup9 { get; set; }
        public virtual DimLookup DimLookup10 { get; set; }
        public virtual DimLookup DimLookup11 { get; set; }
        public virtual DimLookup DimLookup12 { get; set; }
        public virtual DimLookup DimLookup13 { get; set; }
        public virtual DimLookup DimLookup14 { get; set; }
        public virtual DimLookup DimLookup15 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
    }
}
