//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimPatient()
        {
            this.DimActivityTransactions = new HashSet<DimActivityTransaction>();
            this.DimCourses = new HashSet<DimCourse>();
            this.DimPatientDepartments = new HashSet<DimPatientDepartment>();
            this.DimPatientDepartmentbyCUIDs = new HashSet<DimPatientDepartmentbyCUID>();
            this.DimRxes = new HashSet<DimRx>();
            this.FactActivityBillings = new HashSet<FactActivityBilling>();
            this.FactInVivoDosimetries = new HashSet<FactInVivoDosimetry>();
            this.DimPatientPhotoes = new HashSet<DimPatientPhoto>();
            this.FactDVHs = new HashSet<FactDVH>();
            this.DimPatientJournals = new HashSet<DimPatientJournal>();
            this.DimPatientUserDefinedLabels = new HashSet<DimPatientUserDefinedLabel>();
            this.DimPatientVisitTrackings = new HashSet<DimPatientVisitTracking>();
            this.DimVisitEventDetails = new HashSet<DimVisitEventDetail>();
            this.FactPatients = new HashSet<FactPatient>();
            this.FactPatientAllergies = new HashSet<FactPatientAllergy>();
            this.FactPatientDiagnosis = new HashSet<FactPatientDiagnosi>();
            this.FactPatientExams = new HashSet<FactPatientExam>();
            this.FactPatientFamilyHistories = new HashSet<FactPatientFamilyHistory>();
            this.FactPatientImages = new HashSet<FactPatientImage>();
            this.FactPatientLabResults = new HashSet<FactPatientLabResult>();
            this.FactPatientMedicalHistories = new HashSet<FactPatientMedicalHistory>();
            this.FactPatientMedoncTreatments = new HashSet<FactPatientMedoncTreatment>();
            this.FactPatientPayors = new HashSet<FactPatientPayor>();
            this.FactPatientPrescriptions = new HashSet<FactPatientPrescription>();
            this.FactPatientSocialHistories = new HashSet<FactPatientSocialHistory>();
            this.FactPatientToxicities = new HashSet<FactPatientToxicity>();
            this.FactPhysicianOrders = new HashSet<FactPhysicianOrder>();
            this.FactQuestionnaires = new HashSet<FactQuestionnaire>();
            this.FactRxDispSyringes = new HashSet<FactRxDispSyringe>();
            this.FactTreatmentHistories = new HashSet<FactTreatmentHistory>();
        }
    
        public long DimPatientID { get; set; }
        public string PatientId { get; set; }
        public string PatientId2 { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientFullName { get; set; }
        public string PatientHonorific { get; set; }
        public Nullable<System.DateTime> PatientDateOfBirth { get; set; }
        public string PatientType { get; set; }
        public string PatientSSN { get; set; }
        public string PatientLanguage { get; set; }
        public string PatientAddressLine1 { get; set; }
        public string PatientAddressLine2 { get; set; }
        public string PatientFullAddress { get; set; }
        public string PatientAddressComment { get; set; }
        public string PatientHomePhone { get; set; }
        public string PatientWorkPhone { get; set; }
        public string PatientMobilePhone { get; set; }
        public string PatientPagerNumber { get; set; }
        public string PatientEMailAddress { get; set; }
        public string PatientLocation { get; set; }
        public string PatientInOutStatus { get; set; }
        public string PatientDeathStatus { get; set; }
        public string PatientDeathCause { get; set; }
        public Nullable<System.DateTime> PatientDeathDate { get; set; }
        public string ClinicalTrial { get; set; }
        public string PatientComment { get; set; }
        public string PatientNotes { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryUserName { get; set; }
        public string PatientRoomNumber { get; set; }
        public string PatientEmergencyContactAddress { get; set; }
        public string PatientEmergencyContactComment { get; set; }
        public Nullable<int> PatientEmergencyContactEntrusted { get; set; }
        public string PatientEmergencyContactFullName { get; set; }
        public string PatientEmergencyContactHomePhone { get; set; }
        public string PatientEmergencyContactMobilePhone { get; set; }
        public string PatientEmergencyContactWorkPhone { get; set; }
        public string PatientEmergencyContactRelationship { get; set; }
        public string TransportationName { get; set; }
        public string TransportationPhone { get; set; }
        public Nullable<int> NoAlcoholUsePerWeek { get; set; }
        public Nullable<decimal> NoPacksPerDay { get; set; }
        public Nullable<int> NoYearsQuitAlcohol { get; set; }
        public Nullable<int> NoYearsQuitSmoking { get; set; }
        public Nullable<int> NoYearsActiveSmoker { get; set; }
        public string HazardMaterialContactIndicator { get; set; }
        public string AlcoholUseStatus { get; set; }
        public string SmokingUseStatus { get; set; }
        public Nullable<int> ctrPatientSocialHistoryId { get; set; }
        public long ctrPatientSer { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<long> ctrHospitalSer { get; set; }
        public Nullable<long> ctrPrimaryOncologistSer { get; set; }
        public Nullable<long> ctrPrimaryReferringPhysicianSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public string PatientMiddleName { get; set; }
        public string UniversalPatientId { get; set; }
        public string PatientMaritalStatus { get; set; }
        public string PatientOccupation { get; set; }
        public string PatientPresentEmployerName { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public string Ethnicity { get; set; }
        public string Religion { get; set; }
        public string MotherMaidenName { get; set; }
        public string HealthCaredpoa { get; set; }
        public string DoNotResuscitate { get; set; }
        public string DoNotHospitalize { get; set; }
        public string HasLivingWill { get; set; }
        public string IsAutopsyRequested { get; set; }
        public string FeedingRestrictions { get; set; }
        public string IsOrganDonor { get; set; }
        public string BirthPlace { get; set; }
        public string MedicationRestrictions { get; set; }
        public string TreatmentRestrictions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimCourse> DimCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientDepartment> DimPatientDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientDepartmentbyCUID> DimPatientDepartmentbyCUIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimRx> DimRxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityBilling> FactActivityBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactInVivoDosimetry> FactInVivoDosimetries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientPhoto> DimPatientPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactDVH> FactDVHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientJournal> DimPatientJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientUserDefinedLabel> DimPatientUserDefinedLabels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimPatientVisitTracking> DimPatientVisitTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimVisitEventDetail> DimVisitEventDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatient> FactPatients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientAllergy> FactPatientAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientDiagnosi> FactPatientDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientExam> FactPatientExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientFamilyHistory> FactPatientFamilyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientImage> FactPatientImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientLabResult> FactPatientLabResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedicalHistory> FactPatientMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientMedoncTreatment> FactPatientMedoncTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientPayor> FactPatientPayors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientPrescription> FactPatientPrescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientSocialHistory> FactPatientSocialHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPhysicianOrder> FactPhysicianOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactRxDispSyringe> FactRxDispSyringes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactTreatmentHistory> FactTreatmentHistories { get; set; }
    }
}
