//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimQuestionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimQuestionnaire()
        {
            this.FactQuestionnaires = new HashSet<FactQuestionnaire>();
        }
    
        public long DimQuestionnairesID { get; set; }
        public Nullable<long> DimLookupID_QuestionType { get; set; }
        public Nullable<long> DimLookupID_QuestionnaireType { get; set; }
        public string QuestionnaireTitle { get; set; }
        public string QuestionnaireStatus { get; set; }
        public string QuestionNumber { get; set; }
        public string QuestionTag { get; set; }
        public string QuestionText { get; set; }
        public string ctrqstr_name { get; set; }
        public Nullable<int> ctrQuestionId { get; set; }
        public string QuestionnairesType { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires { get; set; }
    }
}
