//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimRxAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimRxAdmin()
        {
            this.FactRxAdminDetails = new HashSet<FactRxAdminDetail>();
        }
    
        public long DimRxAdminID { get; set; }
        public Nullable<long> DimRxAgtID { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> ctrRxAdminId { get; set; }
        public Nullable<int> RxAdminSequenceNo { get; set; }
        public string RxAdminAgentName { get; set; }
        public long RxAdminDosageForm_DimLookupID { get; set; }
        public long RxAdminDoseLevel_DimLookupID { get; set; }
        public long RxAdminDatetimeAdministeredID { get; set; }
        public Nullable<int> RxAdminAgentSequenceNo { get; set; }
        public string RxAdminAsAdvised { get; set; }
        public Nullable<decimal> RxAdminDose { get; set; }
        public string RxAdminDoseApproved { get; set; }
        public long RxAdminHowRecorded_DimLookupID { get; set; }
        public long RxAdminBy_DimUserID { get; set; }
        public Nullable<decimal> RxAdminNoDosesTaken { get; set; }
        public long RxAdminExpectedDateTimeID { get; set; }
        public long RxAdminEnteredBy_DimUserID { get; set; }
        public Nullable<System.DateTime> RxAdminEnteredDatetime { get; set; }
        public long RxAdminLastModifiedby_DimUserID { get; set; }
        public Nullable<System.DateTime> RxAdminLastModifiedDatetime { get; set; }
        public long RxAdminAdminRoute_DimLookupID { get; set; }
        public long RxAdminAdminRouteUnit_DimLookupID { get; set; }
        public string RxAdminValidEntry { get; set; }
        public string RxAdminCourseAdjustIndicator { get; set; }
        public long RxAdminStopDatetimeID { get; set; }
        public string RxAdminVarianceIndicator { get; set; }
        public string RxAdminErrorReason { get; set; }
        public long RxAdminDispenseVerifiedDatetimeID { get; set; }
        public string RxAdminDispensedIndicator { get; set; }
        public string RxAdminCourseDescription { get; set; }
        public string RxAdminCorrected { get; set; }
        public string RxAdminAdhocEntry { get; set; }
        public string RxAdminNotDispensedIndicator { get; set; }
        public Nullable<int> RxAdminDispensingLocation { get; set; }
        public Nullable<int> RxAdminCycleNo { get; set; }
        public Nullable<int> RxAdminCycleDay { get; set; }
        public Nullable<decimal> RxAdminWastage { get; set; }
        public long RxAdminWastageUnit_DimLookupID { get; set; }
        public Nullable<int> RxAdminRevisionNo { get; set; }
        public string RxAdminDrugLotNo { get; set; }
        public Nullable<int> RxAdminManufacturer { get; set; }
        public string RxAdminDisclosedFlag { get; set; }
        public string RxAdminRefusedIndicator { get; set; }
        public long RxAdminExpiryDateID { get; set; }
        public string RxAdminStatus { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimRxAgt DimRxAgt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactRxAdminDetail> FactRxAdminDetails { get; set; }
    }
}
