//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimResource()
        {
            this.DimActivityTransactions = new HashSet<DimActivityTransaction>();
            this.DimUsers = new HashSet<DimUser>();
            this.DimResourceDepartmentHospitals = new HashSet<DimResourceDepartmentHospital>();
            this.FactPatientToxicities = new HashSet<FactPatientToxicity>();
            this.FactQuestionnaires = new HashSet<FactQuestionnaire>();
        }
    
        public long DimResourceID { get; set; }
        public Nullable<long> DimLookupID_ResourceType { get; set; }
        public long ActualResourceID { get; set; }
        public Nullable<long> ctrResourceSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public string ctrstkh_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimActivityTransaction> DimActivityTransactions { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimUser> DimUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimResourceDepartmentHospital> DimResourceDepartmentHospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactQuestionnaire> FactQuestionnaires { get; set; }
    }
}
