//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimRxAgt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimRxAgt()
        {
            this.DimRxAdmins = new HashSet<DimRxAdmin>();
            this.FactRxAdminAgtLevels = new HashSet<FactRxAdminAgtLevel>();
            this.FactRxDispensaries = new HashSet<FactRxDispensary>();
        }
    
        public long DimRxAgtID { get; set; }
        public long DimRxID { get; set; }
        public long DimRxHydraID { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> ctrpt_visit_id { get; set; }
        public Nullable<int> ctrrx_id { get; set; }
        public Nullable<int> ctrRxAgtItemNo { get; set; }
        public string RxAgtAgentName { get; set; }
        public long DimLookupID_RxAgtDosageForm { get; set; }
        public long DimLookupID_RxAgtDoseLevel { get; set; }
        public Nullable<decimal> RxAgtRxDose { get; set; }
        public Nullable<decimal> RxAgtRxTotal { get; set; }
        public long DimLookupID_RxAgtDosageUnit { get; set; }
        public Nullable<int> RxAdminRoute { get; set; }
        public long DimLookupID_RxDoseFrequencyUnit { get; set; }
        public Nullable<int> RxAdminFrequency { get; set; }
        public long DimLookupID_RxAdminFrequencyUnit { get; set; }
        public Nullable<int> RxDuration { get; set; }
        public long DimLookupID_RxDurationUnit { get; set; }
        public string RxRequired { get; set; }
        public string RxAgtStatus { get; set; }
        public string RxSubstitutionsAllowed { get; set; }
        public long RxDiscontinueDateID { get; set; }
        public long RxAdminStartDateID { get; set; }
        public string RxSubstitutionReason { get; set; }
        public string RxDiscontinueReason { get; set; }
        public long RxDiscontinueEffectiveDateID { get; set; }
        public string RxPrnIndicator { get; set; }
        public string RxPrnRepeatIndicator { get; set; }
        public Nullable<decimal> RxDoseRange { get; set; }
        public Nullable<decimal> RxStrength { get; set; }
        public long DimLookupID_RxStrengthUnit { get; set; }
        public long RxTpInitDateID { get; set; }
        public Nullable<decimal> RxDispenseQuantity { get; set; }
        public string RxCourseDescription { get; set; }
        public long DimLookupID_RxDayofWeekFrequencyUnit { get; set; }
        public long DimLookupID_RxWeekFrequencyUnit { get; set; }
        public string RxPlacerOrderNo { get; set; }
        public long DimLookupID_RxOrderUnit { get; set; }
        public Nullable<decimal> RxOrderDose { get; set; }
        public Nullable<int> RxAgtSequenceNo { get; set; }
        public long DimLookupID_RxInfusionType { get; set; }
        public Nullable<int> RxInfusionDuration { get; set; }
        public long DimLookupID_RxInfusionTimescale { get; set; }
        public string RxAgtValidEntryInd { get; set; }
        public long DimLookupID_RxPrnReason { get; set; }
        public long DimLookupID_RxAgtRxType { get; set; }
        public string RxRefillIndicator { get; set; }
        public Nullable<int> RxRefillQuantity { get; set; }
        public string RxDispensedIndicator { get; set; }
        public string RxDoseStrength { get; set; }
        public Nullable<decimal> RxAgentVolume { get; set; }
        public long DimLookupID_RxAgentVolumeUnit { get; set; }
        public string RxDispenseDoseLevelIndicator { get; set; }
        public string RxDoseRecordIndicator { get; set; }
        public string RxAgtInactivateIndicator { get; set; }
        public long DimUserID_RxAgtRxEnteredBy { get; set; }
        public Nullable<System.DateTime> RxAgtRxEnteredTime { get; set; }
        public long DimUserID_RxAgtLastModifiedBy { get; set; }
        public Nullable<System.DateTime> RxAgtLastModifiedTime { get; set; }
        public Nullable<decimal> RxAgtDosePercent { get; set; }
        public string RxAgtChangeIndicator { get; set; }
        public string RxAdhocActiveEntry { get; set; }
        public Nullable<int> RxAgtCycleNo { get; set; }
        public Nullable<int> RxAgtCycleDay { get; set; }
        public string RxAgtTakeAsDirected { get; set; }
        public Nullable<decimal> RxDispenseVolume { get; set; }
        public long DimLookupID_RxDispenseUnit { get; set; }
        public Nullable<int> RxAdminFrequencyUpper { get; set; }
        public string RxAgtNotDispensedIndicator { get; set; }
        public Nullable<int> RxDispenseLocation { get; set; }
        public string RxOverrideDoseTimesIndicator { get; set; }
        public string RxSynchronizeDoseTimesIndicator { get; set; }
        public string RxReviewRequiredIndicator { get; set; }
        public string RxContinueRxIndicator { get; set; }
        public string RxAdminDoseChange { get; set; }
        public Nullable<int> RxAdminDosesRecorded { get; set; }
        public Nullable<int> RxAdminDoseTotal { get; set; }
        public Nullable<int> RxDosesonHold { get; set; }
        public string RxApp_cd { get; set; }
        public string RxTpName { get; set; }
        public string RxTpVersion { get; set; }
        public Nullable<int> RxTpPhase { get; set; }
        public string RxReason { get; set; }
        public string RxHydrationOverrideComment { get; set; }
        public long DimUserID_RxHydrationOverriddenBy { get; set; }
        public long RxHydrationOverrideDatetimeID { get; set; }
        public string RxAgentLevelStatus { get; set; }
        public Nullable<int> RxAgentDisplayOrder { get; set; }
        public string RxConcentration { get; set; }
        public string RxImmunizationCode { get; set; }
        public long RxImmunizationPresentedDateID { get; set; }
        public long RxImmunizationPublishedDateID { get; set; }
        public long DimUserID_RxImmunizationEnteredBy { get; set; }
        public Nullable<System.DateTime> RxImmunizationEnteredDatetime { get; set; }
        public long DimUserID_RxImmunizationLastModifiedBy { get; set; }
        public Nullable<System.DateTime> RxImmunizationLastModifiedDatetime { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimRx DimRx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimRxAdmin> DimRxAdmins { get; set; }
        public virtual DimRxHydra DimRxHydra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactRxAdminAgtLevel> FactRxAdminAgtLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactRxDispensary> FactRxDispensaries { get; set; }
    }
}
