//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimResourceDepartmentHospital
    {
        public long DimResourceDepartmentHospitalID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<long> DimResourceID { get; set; }
        public string DefaultDepartmentName { get; set; }
        public string AssignedToDepartment { get; set; }
        public string AccessRights { get; set; }
        public Nullable<long> ctrResourceDepartmentSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimResource DimResource { get; set; }
    }
}
