//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimRx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimRx()
        {
            this.DimRxAgts = new HashSet<DimRxAgt>();
            this.DimRxHydras = new HashSet<DimRxHydra>();
        }
    
        public long DimRxID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> ctrpt_visit_id { get; set; }
        public Nullable<int> ctrrx_id { get; set; }
        public string RxStatus { get; set; }
        public long RxDateID { get; set; }
        public Nullable<int> RxPharmacy { get; set; }
        public long RxType_DimLookupID { get; set; }
        public Nullable<int> CopiesPrinted { get; set; }
        public string RxComment { get; set; }
        public Nullable<int> RxPhysicianOrderId { get; set; }
        public long RxEnteredBy_DimUserID { get; set; }
        public Nullable<System.DateTime> RxEnteredTime { get; set; }
        public long RxLastModifiedBy_DimUserID { get; set; }
        public Nullable<System.DateTime> RxLastModifiedTime { get; set; }
        public long RxOrderedBy_DimUserID { get; set; }
        public string RxValidEntry { get; set; }
        public Nullable<int> RxInternalPrints { get; set; }
        public Nullable<int> RxPickupInternalPrints { get; set; }
        public Nullable<int> RxPickupExternalPrints { get; set; }
        public Nullable<long> RxApprovedTimeID { get; set; }
        public string RxTpName { get; set; }
        public string RxTpVersion { get; set; }
        public Nullable<int> RxTpPhase { get; set; }
        public Nullable<int> RxCycleNO { get; set; }
        public Nullable<int> RxCycleDay { get; set; }
        public string RxInteractionCheckingIndicator { get; set; }
        public string RxPlacerOrderNo { get; set; }
        public string RxCompletedIndicator { get; set; }
        public Nullable<int> RxBillAccount { get; set; }
        public string RxDispensedIndicator { get; set; }
        public long RxApprovedBy_DimUserID { get; set; }
        public long RxTreatmentStartDateID { get; set; }
        public string RxNotDispensedIndicator { get; set; }
        public string RxReOrderCommentIndicator { get; set; }
        public string RxReorderReviewIndicator { get; set; }
        public string RxPromptTreatmentStartDateIndicator { get; set; }
        public Nullable<int> RxNoCycles { get; set; }
        public Nullable<int> RxLineOfTreatment { get; set; }
        public string RxCalculationAuditDescription { get; set; }
        public long RxTreatmentIntent_DimLookupID { get; set; }
        public long RxTreatmentUse_DimLookupID { get; set; }
        public long RxPharmacyApprovedBy_DimUserID { get; set; }
        public long RxPharmacyApprovedTimeID { get; set; }
        public long RxPrintedBy_DimUserID { get; set; }
        public string RxErrorReason { get; set; }
        public long RxSupervisingPhysician_DimUserID { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimRxAgt> DimRxAgts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimRxHydra> DimRxHydras { get; set; }
    }
}
