//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimStaff
    {
        public long DimStaffID { get; set; }
        public string StaffFirstName { get; set; }
        public string StaffLastName { get; set; }
        public string StaffFullName { get; set; }
        public string StaffAliasName { get; set; }
        public string StaffHonorific { get; set; }
        public string StaffNameSuffix { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> ResourceTypeNum { get; set; }
        public string StaffObjectStatus { get; set; }
        public string Schedulable { get; set; }
        public string StaffCompleteAddress { get; set; }
        public Nullable<int> IsPrimaryResourceAddress { get; set; }
        public string StaffAddressType { get; set; }
        public string StaffAddressComment { get; set; }
        public string StaffPrimaryPhoneNumber { get; set; }
        public string StaffSecondaryPhoneNumber { get; set; }
        public string StaffPagerNumber { get; set; }
        public string StaffFaxNumber { get; set; }
        public string StaffEMailAddress { get; set; }
        public Nullable<System.DateTime> StaffOriginationDate { get; set; }
        public Nullable<System.DateTime> StaffTerminationDate { get; set; }
        public string StaffProfession { get; set; }
        public string StaffComment { get; set; }
        public string StaffAdvancedPractitionerFlag { get; set; }
        public Nullable<long> ctrResourceSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public string ctrstkh_id { get; set; }
    }
}
