//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimToxicityGradingCriteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimToxicityGradingCriteria()
        {
            this.FactPatientToxicities = new HashSet<FactPatientToxicity>();
        }
    
        public long DimToxicityGradingCriteriaID { get; set; }
        public int gs_author { get; set; }
        public System.DateTime eff_date { get; set; }
        public string tr_typ { get; set; }
        public string ToxicityTypeENU { get; set; }
        public string ToxicityTypeFRA { get; set; }
        public string ToxicityTypeESN { get; set; }
        public string ToxicityTypeCHS { get; set; }
        public string ToxicityTypeDEU { get; set; }
        public string ToxicityTypeITA { get; set; }
        public string ToxicityTypeJPN { get; set; }
        public string ToxicityTypePTB { get; set; }
        public string ToxicityTypeSVE { get; set; }
        public string tr_comp_name { get; set; }
        public string ToxicityComponentNameENU { get; set; }
        public string ToxicityComponentNameFRA { get; set; }
        public string ToxicityComponentNameESN { get; set; }
        public string ToxicityComponentNameCHS { get; set; }
        public string ToxicityComponentNameDEU { get; set; }
        public string ToxicityComponentNameITA { get; set; }
        public string ToxicityComponentNameJPN { get; set; }
        public string ToxicityComponentNamePTB { get; set; }
        public string ToxicityComponentNameSVE { get; set; }
        public int tr_grade { get; set; }
        public Nullable<decimal> tr_min_range { get; set; }
        public Nullable<decimal> tr_max_range { get; set; }
        public Nullable<decimal> upper_margin { get; set; }
        public Nullable<decimal> lower_margin { get; set; }
        public Nullable<decimal> trend { get; set; }
        public string appr_flag { get; set; }
        public string trans_log_userid { get; set; }
        public Nullable<System.DateTime> trans_log_tstamp { get; set; }
        public string trans_log_inst_id { get; set; }
        public string trans_log_muserid { get; set; }
        public Nullable<System.DateTime> trans_log_mtstamp { get; set; }
        public string trans_log_minst_id { get; set; }
        public Nullable<System.DateTime> trans_trf_tstamp { get; set; }
        public string bill_cd { get; set; }
        public Nullable<int> bill_cd_typ_id { get; set; }
        public Nullable<int> cls_scheme_id { get; set; }
        public Nullable<int> grading_criteria_id { get; set; }
        public string tr_grading_enter_desc { get; set; }
        public string GradingDescENU { get; set; }
        public string GradingDescFRA { get; set; }
        public string GradingDescESN { get; set; }
        public string GradingDescCHS { get; set; }
        public string GradingDescDEU { get; set; }
        public string GradingDescITA { get; set; }
        public string GradingDescJPN { get; set; }
        public string GradingDescPTB { get; set; }
        public string GradingDescSVE { get; set; }
        public Nullable<int> LogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPatientToxicity> FactPatientToxicities { get; set; }
    }
}
