//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimVisitEventDetail
    {
        public long DimVisitEventDetailID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<long> DimInstituteLocationID { get; set; }
        public Nullable<long> DimUserID_Provider { get; set; }
        public Nullable<long> DimDateID_StartDateTime { get; set; }
        public Nullable<long> DimDateID_EndDateTime { get; set; }
        public string EventType { get; set; }
        public string EventTypeDescription { get; set; }
        public string PatientIndicator { get; set; }
        public string ProfIndicator { get; set; }
        public string LocationIndicator { get; set; }
        public string PatientUnavailComment { get; set; }
        public Nullable<System.DateTime> EventStartDateTime { get; set; }
        public Nullable<System.DateTime> EventEndDateTime { get; set; }
        public string ValidEntryIndicator { get; set; }
        public Nullable<int> ctrunavl_hdr_id { get; set; }
        public string ctrinst_id { get; set; }
        public Nullable<int> LogID { get; set; }
        public string EventName { get; set; }
        public string SchEventName { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimInstituteLocation DimInstituteLocation { get; set; }
        public virtual DimPatient DimPatient { get; set; }
    }
}
