//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoseContributionModel
    {
        public long ID { get; set; }
        public long PatientSer { get; set; }
        public long CourseSer { get; set; }
        public string CourseId { get; set; }
        public long PlanSetupSer { get; set; }
        public string PlanSetupId { get; set; }
        public long RTPlanSer { get; set; }
        public long RefPointSer { get; set; }
        public string RefPointId { get; set; }
        public Nullable<int> PrimaryRefPoint { get; set; }
        public long RadiationSer { get; set; }
        public string RadiationId { get; set; }
        public Nullable<double> PlannedFieldDose { get; set; }
        public Nullable<double> DeliveredFieldDose { get; set; }
        public Nullable<double> DoseCorrection { get; set; }
        public string CorrectionNote { get; set; }
        public Nullable<System.DateTime> CorrectionDateTime { get; set; }
        public Nullable<long> RefPointLogSer { get; set; }
        public Nullable<long> DoseCorrectionLogSer { get; set; }
    }
}
