//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVHInputParameter
    {
        public long DVHInputParameterID { get; set; }
        public long PatientDbKey { get; set; }
        public long CourseDbKey { get; set; }
        public long PlanDbKey { get; set; }
        public long StructureSetDbKey { get; set; }
        public long StructureDbKey { get; set; }
        public System.DateTime PlanSetUpHstryDateTime { get; set; }
        public System.DateTime StructureHstryDateTime { get; set; }
        public string LoadStatus { get; set; }
        public Nullable<int> LogID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> LastModifyDateTime { get; set; }
    }
}
