//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVHPatientPoint
    {
        public long DimPatientID { get; set; }
        public long DimPlanID { get; set; }
        public long DimStructureID { get; set; }
        public Nullable<double> RelativeVolume { get; set; }
        public string PatientId { get; set; }
        public string PlanSetupId { get; set; }
        public string StructureId { get; set; }
        public string PlanSetupName { get; set; }
    }
}
