//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactRxDispSyringe
    {
        public long FactRxDispSyringeID { get; set; }
        public long DimPatientID { get; set; }
        public Nullable<int> ctrsyringe_id { get; set; }
        public Nullable<int> ctrsyringe_seq_no { get; set; }
        public Nullable<decimal> RxDispSyringeVolume { get; set; }
        public long DimLookupID_RxDispSyringeVolumeUnit { get; set; }
        public long DimUserID_RxDispSyringeEnteredBy { get; set; }
        public Nullable<long> DimDateID_EnteredDatetime { get; set; }
        public long DimUserID_RxDispSyringeLastModifiedBy { get; set; }
        public Nullable<long> DimDateID_LastModifiedDatetime { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimUser DimUser { get; set; }
        public virtual DimUser DimUser1 { get; set; }
    }
}
