//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactQuestionnaire
    {
        public long FactQuestionnairesID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimQuestionnairesID { get; set; }
        public Nullable<long> DimHospitalDepartmentID_Approved { get; set; }
        public Nullable<long> DimResourceID_Author { get; set; }
        public Nullable<long> DimUserID_Approved { get; set; }
        public Nullable<long> DimDateID_ResponseDateTime { get; set; }
        public Nullable<long> DimDateID_ApprovedDateTime { get; set; }
        public Nullable<long> DimDateID_QuestionnaireDateTime { get; set; }
        public string PatientResponse { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public string ResponseValidEntryIndicator { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public Nullable<System.DateTime> QuestionnaireDateTime { get; set; }
        public string ResponseHeaderValidEntryIndicator { get; set; }
        public string TransLogUserId { get; set; }
        public Nullable<System.DateTime> TransLogDateTime { get; set; }
        public string TransLogModifiedUserId { get; set; }
        public Nullable<System.DateTime> TransLogModifiedDateTime { get; set; }
        public Nullable<long> ctrqstr_id { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimQuestionnaire DimQuestionnaire { get; set; }
        public virtual DimResource DimResource { get; set; }
        public virtual DimUser DimUser { get; set; }
    }
}
