//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactVisitNote
    {
        public long FactVisitNoteID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimDateID_VisitNote { get; set; }
        public Nullable<long> DimDateID_Signed { get; set; }
        public Nullable<long> DimDateID_Approved { get; set; }
        public Nullable<long> DimUserID_Override { get; set; }
        public Nullable<long> DimResourceID_Creator { get; set; }
        public Nullable<long> DimResourceID_Author { get; set; }
        public Nullable<long> DimResourceID_AuthorOrg { get; set; }
        public Nullable<long> DimResourceID_ApprovedBy { get; set; }
        public Nullable<long> DimResourceID_SupervisedBy { get; set; }
        public Nullable<long> DimResourceID_SignedBy { get; set; }
        public Nullable<long> DimResourceID_Cert { get; set; }
        public Nullable<long> DimLookupID_NoteType { get; set; }
        public Nullable<long> DimLookupID_ProfType { get; set; }
        public string VisitNoteText { get; set; }
        public string ApprovedFlag { get; set; }
        public string DictatedFlag { get; set; }
        public string OverrideUserId { get; set; }
        public string OverrideText { get; set; }
        public string ValidIndicator { get; set; }
        public string PrivateIndicator { get; set; }
        public string DisciplineType { get; set; }
        public string GeneratedIndicator { get; set; }
        public string CompletedIndicator { get; set; }
        public string RemAttachedIndicator { get; set; }
        public Nullable<int> BillAccountId { get; set; }
        public Nullable<System.DateTime> VisitNoteDateTime { get; set; }
        public Nullable<System.DateTime> SignedDateTime { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public Nullable<int> DocumentSer { get; set; }
        public string TemplateName { get; set; }
        public string ImgDocumentId { get; set; }
        public string TransLogUserId { get; set; }
        public Nullable<System.DateTime> TransLogDateTime { get; set; }
        public string TransLogModifiedUserId { get; set; }
        public Nullable<System.DateTime> TransLogModifiedDateTime { get; set; }
        public Nullable<int> ctrvisit_note_id { get; set; }
        public Nullable<int> ctrpt_visit_id { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> LogID { get; set; }
    }
}
