//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactDVHToxicity
    {
        public long FactDVHToxicityID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> FactPatientToxicityID { get; set; }
        public Nullable<long> DimPlanID { get; set; }
        public Nullable<int> IsAcute { get; set; }
    }
}
