//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPatientPayor
    {
        public long FactPatientPayorID { get; set; }
        public long DimPatientID { get; set; }
        public Nullable<long> DimPayorID { get; set; }
        public Nullable<byte> IsPrimaryPayor { get; set; }
        public Nullable<byte> IsSecondaryPayor { get; set; }
        public string PayorInsuredName { get; set; }
        public string PayorAuthorizationId { get; set; }
        public string PayorComment { get; set; }
        public string PayorPolicyNumber { get; set; }
        public string PayorRelationshipwithInsured { get; set; }
        public string PayorCurrentAccountNumber { get; set; }
        public Nullable<double> PrcntOfPaymnt { get; set; }
        public Nullable<decimal> CoPayment { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<long> ctrPatientPayorSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimPayor DimPayor { get; set; }
    }
}
