//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPatientImage
    {
        public long FactPatientImageID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimCourseID { get; set; }
        public Nullable<long> DimFieldID { get; set; }
        public Nullable<long> DimMachineID { get; set; }
        public Nullable<long> DimDoctorID_Oncologist { get; set; }
        public Nullable<long> DimUserID_ApprovedBy { get; set; }
        public Nullable<long> DimDateID_ApprovalDate { get; set; }
        public Nullable<long> DimDateID_ImageCreationDate { get; set; }
        public Nullable<long> DimLookupID_ImageStatus { get; set; }
        public Nullable<int> Energy { get; set; }
        public string ImageId { get; set; }
        public Nullable<System.DateTime> ImageCreationDate { get; set; }
        public string ImageType { get; set; }
        public string ImageStatus { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ImageNote { get; set; }
        public string Comment { get; set; }
        public Nullable<double> IsocenterX { get; set; }
        public Nullable<double> IsocenterY { get; set; }
        public Nullable<double> IsocenterZ { get; set; }
        public string DicomUID { get; set; }
        public Nullable<double> MetersetExposure { get; set; }
        public Nullable<int> ExposureTime { get; set; }
        public Nullable<int> XRayTubeCurrent { get; set; }
        public string PrimaryDosimeterUnit { get; set; }
        public Nullable<int> ImageNotesLen { get; set; }
        public string CreationUserName { get; set; }
        public Nullable<long> ctrStudySer { get; set; }
        public Nullable<long> ctrSeriesSer { get; set; }
        public Nullable<long> ctrSliceSer { get; set; }
        public Nullable<long> ctrImageSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimCourse DimCourse { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDoctor DimDoctor { get; set; }
        public virtual DimField DimField { get; set; }
        public virtual DimMachine DimMachine { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimUser DimUser { get; set; }
    }
}
