//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactMedOncPrescription
    {
        public long FactMedOncPrescriptionID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimDrugID { get; set; }
        public Nullable<long> DimDateID_RxDateTime { get; set; }
        public Nullable<long> DimLookupID_RxType { get; set; }
        public string RxComment { get; set; }
        public string RxStatus { get; set; }
        public string PlacerOrderNo { get; set; }
        public string RxCompletedInd { get; set; }
        public Nullable<long> DimUserID_RxPrintBy { get; set; }
        public Nullable<long> DimHospitalDepartmentID_Print { get; set; }
        public Nullable<long> DimUserID_RxSupervisor { get; set; }
        public Nullable<long> DimHospitalDepartmentID_Supervisor { get; set; }
        public Nullable<long> DimUserID_RxOrderBy { get; set; }
        public Nullable<long> DimHospitalDepartmentID_OrderBy { get; set; }
        public Nullable<long> DimDateID_RxApprovedDate { get; set; }
        public Nullable<long> DimUserID_RxApprovedBy { get; set; }
        public Nullable<long> DimHospitalDepartmentID_Approver { get; set; }
        public string RxAgentName { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<long> DimLookupID_DosageForm { get; set; }
        public Nullable<int> DoseLevel { get; set; }
        public Nullable<decimal> RxDose { get; set; }
        public Nullable<decimal> RxTotal { get; set; }
        public Nullable<int> RxAdministrationDosageUnit { get; set; }
        public Nullable<long> DimLookupID_AdmnRoute { get; set; }
        public Nullable<long> DimLookupID_AdmnDoseFrqUnit { get; set; }
        public Nullable<int> AdmnFrqX { get; set; }
        public Nullable<int> AdmnFrequencyUnit { get; set; }
        public Nullable<int> RxAdministrationDuration { get; set; }
        public Nullable<int> RxAdministrationDurationUnit { get; set; }
        public string AgentStatus { get; set; }
        public string SubstituteAllowed { get; set; }
        public Nullable<long> DimDateID_RxDiscontinueDate { get; set; }
        public Nullable<long> DimDateID_RxAdministrationStartDate { get; set; }
        public Nullable<System.DateTime> RxApprovedDate { get; set; }
        public Nullable<System.DateTime> RxDiscontinueDate { get; set; }
        public Nullable<System.DateTime> RxAdministrationStartDate { get; set; }
        public string ReasonForSubstitute { get; set; }
        public string GeneralOrders { get; set; }
        public string RxDiscontinueReason { get; set; }
        public Nullable<long> DimDateID_DiscontiueEffectiveDate { get; set; }
        public Nullable<System.DateTime> DiscontiueEffectiveDate { get; set; }
        public string PRNInd { get; set; }
        public Nullable<decimal> RxDoseRange { get; set; }
        public Nullable<decimal> Strength { get; set; }
        public Nullable<int> StrengthUnit { get; set; }
        public string RxCourseDesc { get; set; }
        public Nullable<int> AgentSequenceNo { get; set; }
        public Nullable<long> DimLookupID_PrnReasonType { get; set; }
        public Nullable<int> RefillQty { get; set; }
        public string RxDispensedInd { get; set; }
        public string DoseStrength { get; set; }
        public string AgentRxInd { get; set; }
        public Nullable<decimal> AgentVolume { get; set; }
        public Nullable<int> AgentVolumeUOM { get; set; }
        public Nullable<decimal> RxDosePercent { get; set; }
        public string TakeAsDirectedInd { get; set; }
        public string ReviewRequiredInd { get; set; }
        public Nullable<int> RSNType { get; set; }
        public string RSNDesc { get; set; }
        public Nullable<long> DimUserID_HydraRateOvrideUser { get; set; }
        public Nullable<long> DimHospitalDepartmentID_HydraRateOvrideInst { get; set; }
        public Nullable<int> AgentDisplayOrder { get; set; }
        public string pharm_instr { get; set; }
        public string AltNDC { get; set; }
        public string RxValidEntryInd { get; set; }
        public Nullable<int> ctrrx_id { get; set; }
        public Nullable<int> ctrpt_visit_id { get; set; }
        public Nullable<int> LogID { get; set; }
    }
}
