//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactActivityBilling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactActivityBilling()
        {
            this.FactActivityDiagnosis = new HashSet<FactActivityDiagnosi>();
        }
    
        public long FactActivityBillingID { get; set; }
        public Nullable<long> DimProcedureCodeID { get; set; }
        public Nullable<long> DimActivityID { get; set; }
        public Nullable<long> DimLookupID_ActivityCategory { get; set; }
        public Nullable<long> DimResourceID_Activity { get; set; }
        public long DimActivityTransactionID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimCourseID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<long> DimDoctorID { get; set; }
        public Nullable<long> DimDoctorID_AttendingOncologist { get; set; }
        public Nullable<long> DimUserID_MarkedCompletedBy { get; set; }
        public Nullable<long> DimUserID_ExportedBy { get; set; }
        public Nullable<long> DimUserID_ChargeWaivedBy { get; set; }
        public Nullable<long> DimUserID_ReviewedBy { get; set; }
        public Nullable<long> DimUserID_CreditedBy { get; set; }
        public Nullable<long> DimDateID_FromDateOfService { get; set; }
        public Nullable<long> DimDateID_ToDateOfService { get; set; }
        public Nullable<long> DimDateID_CompletedDateTime { get; set; }
        public Nullable<long> DimDateID_ExportedDateTime { get; set; }
        public Nullable<long> DimDateID_MarkedCompletedDateTime { get; set; }
        public Nullable<long> DimDateID_CreditExportedDateTime { get; set; }
        public Nullable<long> DimDateID_CreditedDateTime { get; set; }
        public Nullable<long> DimDateID_TemplateCreationDate { get; set; }
        public Nullable<decimal> PrimaryGlobalCharge { get; set; }
        public Nullable<decimal> PrimaryTechnicalCharge { get; set; }
        public Nullable<decimal> PrimaryProfessionalCharge { get; set; }
        public Nullable<decimal> OtherProfessionalCharge { get; set; }
        public Nullable<decimal> OtherTechnicalCharge { get; set; }
        public Nullable<decimal> OtherGlobalCharge { get; set; }
        public Nullable<decimal> ChargeForecast { get; set; }
        public Nullable<decimal> ActualCharge { get; set; }
        public Nullable<double> ProfessionalRVU { get; set; }
        public Nullable<double> GlobalRVU { get; set; }
        public Nullable<double> TechnicalRVU { get; set; }
        public Nullable<decimal> ActivityCost { get; set; }
        public Nullable<double> WorkUnit { get; set; }
        public string AccountBillingCode { get; set; }
        public Nullable<System.DateTime> FromDateOfService { get; set; }
        public Nullable<System.DateTime> ToDateOfService { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<System.DateTime> ExportedDateTime { get; set; }
        public Nullable<System.DateTime> MarkedCompletedDateTime { get; set; }
        public Nullable<System.DateTime> CreditExportedDateTime { get; set; }
        public Nullable<System.DateTime> CreditedDateTime { get; set; }
        public string CreditNote { get; set; }
        public string AllModifierCodes { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string IsScheduled { get; set; }
        public string DiagnosisId { get; set; }
        public string ObjectStatus { get; set; }
        public string ActivityInstance_ObjectStatus { get; set; }
        public string ActInstProcCode_ObjectStatus { get; set; }
        public Nullable<int> ActivityCaptureRevCount { get; set; }
        public Nullable<int> ActivityInstanceRevCount { get; set; }
        public Nullable<int> ActivityCodeMdRevCount { get; set; }
        public Nullable<int> ProcedureCodeRevCount { get; set; }
        public Nullable<int> AccountBillingCodeRevCount { get; set; }
        public Nullable<int> ActInstProcCodeRevCount { get; set; }
        public Nullable<int> CreditRevCount { get; set; }
        public string TemplateID { get; set; }
        public Nullable<int> TemplateRevCount { get; set; }
        public Nullable<System.DateTime> TemplateCreationDate { get; set; }
        public string PatientStatus { get; set; }
        public string InPatientFlag { get; set; }
        public Nullable<long> ctrActivityInstanceSer { get; set; }
        public Nullable<long> ctrTemplateSer { get; set; }
        public Nullable<long> ctrTemplateCycleSer { get; set; }
        public Nullable<long> ctrActivityCaptureSer { get; set; }
        public Nullable<long> ctrActInstProcCodeSer { get; set; }
        public Nullable<long> ctrAccountBillingCodeSer { get; set; }
        public Nullable<long> ctrCreditSer { get; set; }
        public string ctrDiagnosisSer { get; set; }
        public Nullable<long> ctrActivityCategorySer { get; set; }
        public Nullable<long> ctrResourceSer_Activity { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<long> DimUserID_CompletedByUser { get; set; }
        public string BillEventDescription { get; set; }
        public Nullable<long> DimLookupID_BillEventType { get; set; }
        public Nullable<int> BillEventUnits { get; set; }
        public string BillEventStatus { get; set; }
        public string BillingInventoryID { get; set; }
        public string BillItemDescription { get; set; }
        public Nullable<long> DimDrugID { get; set; }
        public Nullable<int> BillingAccountID { get; set; }
        public Nullable<long> DimInstituteLocationID { get; set; }
        public string OverrideIndicator { get; set; }
        public Nullable<long> DimDoctorID_Referring { get; set; }
        public Nullable<double> DoseWastageAmount { get; set; }
        public Nullable<long> DimLookupID_DoseWastageUnit { get; set; }
        public Nullable<long> DimDiagnosisCodeID { get; set; }
        public Nullable<int> ctrbill_event_id { get; set; }
        public string MOROIndicator { get; set; }
        public Nullable<long> DimUserID_Physician { get; set; }
    
        public virtual DimActivity DimActivity { get; set; }
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimCourse DimCourse { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimDate DimDate3 { get; set; }
        public virtual DimDate DimDate4 { get; set; }
        public virtual DimDate DimDate5 { get; set; }
        public virtual DimDate DimDate6 { get; set; }
        public virtual DimDate DimDate7 { get; set; }
        public virtual DimDiagnosisCode DimDiagnosisCode { get; set; }
        public virtual DimDoctor DimDoctor { get; set; }
        public virtual DimDoctor DimDoctor1 { get; set; }
        public virtual DimDoctor DimDoctor2 { get; set; }
        public virtual DimDrug DimDrug { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimInstituteLocation DimInstituteLocation { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        public virtual DimLookup DimLookup2 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimProcedureCode DimProcedureCode { get; set; }
        public virtual DimUser DimUser { get; set; }
        public virtual DimUser DimUser1 { get; set; }
        public virtual DimUser DimUser2 { get; set; }
        public virtual DimUser DimUser3 { get; set; }
        public virtual DimUser DimUser4 { get; set; }
        public virtual DimUser DimUser5 { get; set; }
        public virtual DimUser DimUser6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityDiagnosi> FactActivityDiagnosis { get; set; }
    }
}
