//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactRxDispensary
    {
        public long FactRxDispensaryID { get; set; }
        public long DimRxAgtID { get; set; }
        public Nullable<int> ctrdisp_id { get; set; }
        public Nullable<int> ctrsyringe_id { get; set; }
        public long DimDateID_RxDispDate { get; set; }
        public long DimDateID_ExpiryDateID { get; set; }
        public Nullable<long> DimDateID_HydraOverriddenDateTime { get; set; }
        public long DimUserID_RxDispBy { get; set; }
        public long DimUserID_RxDispEnteredBy { get; set; }
        public long DimUserID_RxDispLastModifiedBy { get; set; }
        public long DImUserID_RxDispHydraOverriddenBy { get; set; }
        public long DimLookupID_RxDispDosageForm { get; set; }
        public long DimLookupID_RxDispDoseUnit { get; set; }
        public long DimLookupID_RxDispAdminRoute { get; set; }
        public long DimLookupID_RxDispDoseStrengthUnit { get; set; }
        public long DimLookupID_RxDispInfusionType { get; set; }
        public long DimLookupID_RxDispInfusionDurationUnit { get; set; }
        public long DimLookupID_RxDispOrderUnit { get; set; }
        public long DimLookupID_RxDispSyringeVolumeUnit { get; set; }
        public long DimLookupID_RxDispAgentVolumeUnit { get; set; }
        public long DimLookupID_RxDispUnit { get; set; }
        public Nullable<System.DateTime> RxDispEnteredDatetime { get; set; }
        public Nullable<System.DateTime> RxDispLastModifiedDatetime { get; set; }
        public string RxDispComment { get; set; }
        public string RxDispApproved { get; set; }
        public string RxDispValidEntry { get; set; }
        public string RxDispAgentName { get; set; }
        public Nullable<decimal> RxDispDispensedDose { get; set; }
        public Nullable<decimal> RxDispDispensedDoseRange { get; set; }
        public Nullable<decimal> RxDispOrderDose { get; set; }
        public string RxDispDoseStrength { get; set; }
        public Nullable<int> RxDispInfusionDuration { get; set; }
        public Nullable<int> RxDispSyringeQuantity { get; set; }
        public Nullable<decimal> RxDispSyringeVolume { get; set; }
        public string RxDispChangeIndicator { get; set; }
        public Nullable<decimal> RxDispAgentVolume { get; set; }
        public Nullable<int> RxDispHydraDispenseId { get; set; }
        public string RxDispCourseDescription { get; set; }
        public string RxDispErrorReason { get; set; }
        public string RxDispNotDispensedIndicator { get; set; }
        public Nullable<decimal> RxDispDispenseQuantity { get; set; }
        public Nullable<decimal> RxDispDispenseVolume { get; set; }
        public string RxDispPlacerOrderNo { get; set; }
        public string RxDispHydraOverrideReason { get; set; }
        public string RxDispCustomSyringeIndicator { get; set; }
        public string RxDispReviewIndicator { get; set; }
        public string RxDispConcentration { get; set; }
        public string RxDispFormularyChecked { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimRxAgt DimRxAgt { get; set; }
    }
}
