//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPhysicianOrder
    {
        public long FactPhysicianOrderID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimHospitalDepartmentID { get; set; }
        public Nullable<long> DimDateID_AppliedDateTime { get; set; }
        public Nullable<long> DimUserID_AppliedUser { get; set; }
        public Nullable<long> DimDateID_PhysicianOrderTimeFrame { get; set; }
        public Nullable<long> DimDateID_VerbalApproved { get; set; }
        public Nullable<long> DimDateID_Verbal { get; set; }
        public Nullable<long> DimUserID_Verbal { get; set; }
        public Nullable<long> DimLookupID_OrderType { get; set; }
        public Nullable<long> DimLookupID_TimeFrame { get; set; }
        public Nullable<long> DimUserID_OrderCreatedBy { get; set; }
        public string AppliedIndicator { get; set; }
        public Nullable<System.DateTime> AppliedDateTime { get; set; }
        public string AppliedText { get; set; }
        public string ApprovedOnFileIndicator { get; set; }
        public string CancelEntryIndicator { get; set; }
        public string CompletedIndicator { get; set; }
        public string GeneratedIndicator { get; set; }
        public string PlacerOrderNumber { get; set; }
        public string PlanAffectIndicator { get; set; }
        public string PhysicianOrderSheetDesc { get; set; }
        public Nullable<int> PhysicianOrderTimeFrame { get; set; }
        public Nullable<int> PhysicianOrderTime { get; set; }
        public Nullable<System.DateTime> POTimeFrameDateTime { get; set; }
        public string RecurringIndicator { get; set; }
        public Nullable<System.DateTime> TransLogModifiedDateTime { get; set; }
        public string TransLogModifiedUserId { get; set; }
        public Nullable<System.DateTime> TransLogDateTime { get; set; }
        public string TransLogUserId { get; set; }
        public string VerbalOrderValidEntryIndicator { get; set; }
        public string VerbalOrderApprovalFlag { get; set; }
        public Nullable<System.DateTime> VerbalApprovalDateTime { get; set; }
        public string VerbalApprovalText { get; set; }
        public string VerbalComment { get; set; }
        public string DisplaySourceType { get; set; }
        public Nullable<System.DateTime> VerbalDateTime { get; set; }
        public string VerbalText { get; set; }
        public string VerbalType { get; set; }
        public string VerbalTypeDesc { get; set; }
        public string PhysicianOrderDescription { get; set; }
        public string PhysicianOrderDetails { get; set; }
        public string PhysicianOrderCategory { get; set; }
        public string PhysicianOrderDescText { get; set; }
        public string TreatmentPlanName { get; set; }
        public string TreatmentPlanVersionNumber { get; set; }
        public Nullable<System.DateTime> TreatmentPlanInitDateTime { get; set; }
        public string ExternalTreatmentPlanName { get; set; }
        public string ctrpt_id { get; set; }
        public Nullable<int> ctrvrbl_id { get; set; }
        public Nullable<int> ctrvrbl_order_detail_id { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimUser DimUser { get; set; }
        public virtual DimUser DimUser1 { get; set; }
    }
}
