//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPatientDiagnosi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactPatientDiagnosi()
        {
            this.FactActivityDiagnosis = new HashSet<FactActivityDiagnosi>();
            this.FactCourseDiagnosis = new HashSet<FactCourseDiagnosi>();
        }
    
        public long FactPatientDiagnosisID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimDiagnosisCodeID { get; set; }
        public Nullable<long> DimICDOSiteID { get; set; }
        public Nullable<long> DimCellTypeID { get; set; }
        public Nullable<long> DimLookupID_DiagnosisStatus { get; set; }
        public Nullable<long> DimLookupID_Ranking { get; set; }
        public Nullable<long> DimLookupID_Source { get; set; }
        public Nullable<long> DimLookupID_HistoricDxFlag { get; set; }
        public Nullable<long> DimLookupID_CellCategory { get; set; }
        public Nullable<long> DimLookupID_CellGrade { get; set; }
        public Nullable<long> DimLookupID_Laterality { get; set; }
        public Nullable<long> DimLookupID_Stage { get; set; }
        public Nullable<long> DimLookupID_StageStatus { get; set; }
        public Nullable<long> DimLookupID_ERStatus { get; set; }
        public Nullable<long> DimLookupID_PRStatus { get; set; }
        public Nullable<long> DimLookupID_Her2neuMethodType { get; set; }
        public Nullable<long> DimLookupID_Her2neuStatusType { get; set; }
        public Nullable<long> DimLookupID_Her2neuMethod2Type { get; set; }
        public Nullable<long> DimLookupID_Her2neuStatus2Type { get; set; }
        public Nullable<long> DimLookupID_Recurrence { get; set; }
        public Nullable<long> DimLookupID_Invasive { get; set; }
        public Nullable<long> DimLookupID_ConfirmedDx { get; set; }
        public Nullable<long> DimLookupID_DiagnosisType { get; set; }
        public Nullable<long> DimLookupID_DxMethodType { get; set; }
        public Nullable<long> DimLookupID_ICDOVersion { get; set; }
        public Nullable<long> DimDxSiteID_BodySystem { get; set; }
        public Nullable<long> DimDxSiteID { get; set; }
        public Nullable<long> DimDateID_DiagnosisStatusDate { get; set; }
        public string DxDate { get; set; }
        public Nullable<System.DateTime> DiagnosisStatusDate { get; set; }
        public string DiagnosisDescription { get; set; }
        public string ClinicalDescription { get; set; }
        public string HistoricDetails { get; set; }
        public string Comments { get; set; }
        public string PathologyComments { get; set; }
        public string Behaviour { get; set; }
        public string DistantMets { get; set; }
        public Nullable<int> Nodes { get; set; }
        public Nullable<int> NodesPositive { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string StageCriteria { get; set; }
        public string Stagebasis { get; set; }
        public string StageScheme { get; set; }
        public Nullable<decimal> SPhase { get; set; }
        public string MethodDescription { get; set; }
        public Nullable<int> CoresTaken { get; set; }
        public Nullable<int> CoresPositive { get; set; }
        public Nullable<int> GleasonPrimary { get; set; }
        public Nullable<int> GleasonSecondary { get; set; }
        public Nullable<int> GleasonTotal { get; set; }
        public Nullable<int> GleasonScore { get; set; }
        public string ObjectStatus { get; set; }
        public string HistologyCode { get; set; }
        public string HistologyTableName { get; set; }
        public string TStage { get; set; }
        public string NStage { get; set; }
        public string MStage { get; set; }
        public string SummaryStage { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<int> ctrDiagnosisID { get; set; }
        public Nullable<long> ctrDiagnosisSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public string CurrentEntry { get; set; }
        public string CancerDescription { get; set; }
        public string CancerStatus { get; set; }
        public string LesionDescription { get; set; }
        public Nullable<int> LesionOrder { get; set; }
        public Nullable<int> LesionDimention { get; set; }
        public Nullable<long> DimLookupID_LesionMeasurable { get; set; }
        public Nullable<int> PrimaryCancerID { get; set; }
        public Nullable<int> PrimaryDiagnosisId { get; set; }
        public Nullable<System.DateTime> DateStaged { get; set; }
        public Nullable<int> ctrpt_stage_id { get; set; }
        public Nullable<long> DimDxSiteID_PrimaryCancerSite { get; set; }
        public string PatientCancerStageCreatedBy { get; set; }
        public Nullable<System.DateTime> PatientCancerStageDateTime { get; set; }
        public Nullable<System.DateTime> PtDxOnSetDate { get; set; }
        public Nullable<System.DateTime> PtDxLastModifiedDateTime { get; set; }
        public Nullable<System.DateTime> PtDxCncrLastModifiedDateTime { get; set; }
        public Nullable<System.DateTime> DxSiteDateTime { get; set; }
    
        public virtual DimCellType DimCellType { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDiagnosisCode DimDiagnosisCode { get; set; }
        public virtual DimDxSite DimDxSite { get; set; }
        public virtual DimDxSite DimDxSite1 { get; set; }
        public virtual DimDxSite DimDxSite2 { get; set; }
        public virtual DimICDOSite DimICDOSite { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        public virtual DimLookup DimLookup2 { get; set; }
        public virtual DimLookup DimLookup3 { get; set; }
        public virtual DimLookup DimLookup4 { get; set; }
        public virtual DimLookup DimLookup5 { get; set; }
        public virtual DimLookup DimLookup6 { get; set; }
        public virtual DimLookup DimLookup7 { get; set; }
        public virtual DimLookup DimLookup8 { get; set; }
        public virtual DimLookup DimLookup9 { get; set; }
        public virtual DimLookup DimLookup10 { get; set; }
        public virtual DimLookup DimLookup11 { get; set; }
        public virtual DimLookup DimLookup12 { get; set; }
        public virtual DimLookup DimLookup13 { get; set; }
        public virtual DimLookup DimLookup14 { get; set; }
        public virtual DimLookup DimLookup15 { get; set; }
        public virtual DimLookup DimLookup16 { get; set; }
        public virtual DimLookup DimLookup17 { get; set; }
        public virtual DimLookup DimLookup18 { get; set; }
        public virtual DimLookup DimLookup19 { get; set; }
        public virtual DimLookup DimLookup20 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactActivityDiagnosi> FactActivityDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactCourseDiagnosi> FactCourseDiagnosis { get; set; }
    }
}
