//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactInVivoDosimetry
    {
        public long FactInVivoDosimetryID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimDateID_InVivoDate { get; set; }
        public string UserName { get; set; }
        public Nullable<long> DimUserID_CreationUserName { get; set; }
        public Nullable<long> DimDateID_CreationDate { get; set; }
        public Nullable<System.DateTime> InVivoDate { get; set; }
        public string InVivoVendorName { get; set; }
        public string DosimeterType { get; set; }
        public string DosimeterId { get; set; }
        public string DosimeterLocation { get; set; }
        public string FieldId { get; set; }
        public string FieldName { get; set; }
        public Nullable<double> ExpectedDose { get; set; }
        public Nullable<double> DeliveredDose { get; set; }
        public Nullable<double> ToleranceValue { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string PlanUID { get; set; }
        public Nullable<int> FieldGroupNumber { get; set; }
        public string ObjectStatus { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public Nullable<System.DateTime> HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public Nullable<long> ctrInVivoDosimetrySer { get; set; }
        public Nullable<long> ctrPatientSer { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimUser DimUser { get; set; }
    }
}
