//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPatientMedicalHistory
    {
        public long FactPatientMedicalHistoryID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimLookupID_MpauseReasonType { get; set; }
        public Nullable<long> DimDateID_DiagnosisDate { get; set; }
        public Nullable<long> DimDateID_MrPapDate { get; set; }
        public Nullable<long> DimDateID_MrMammogramDate { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<System.DateTime> DiagnosisDate { get; set; }
        public string ActiveDiagnosisIndicator { get; set; }
        public string TreatmentIndicator { get; set; }
        public Nullable<int> Gravida { get; set; }
        public Nullable<int> Para { get; set; }
        public Nullable<int> NoAbortions { get; set; }
        public Nullable<int> AgeAtFirstBirth { get; set; }
        public Nullable<int> MensesStartAge { get; set; }
        public string MpauseCode { get; set; }
        public string MpauseDescription { get; set; }
        public Nullable<int> MpauseAge { get; set; }
        public string OcpUseIndicator { get; set; }
        public Nullable<int> OcpUseDuration { get; set; }
        public string MpauseHormoneIndicator { get; set; }
        public Nullable<int> MpauseHormoneDuration { get; set; }
        public string OtherHormoneUseIndicator { get; set; }
        public Nullable<int> OtherHormoneDuration { get; set; }
        public Nullable<System.DateTime> MrPapDate { get; set; }
        public Nullable<System.DateTime> MrMammogramDate { get; set; }
        public string CurrentEntryIndicator { get; set; }
        public Nullable<int> MpauseCycle { get; set; }
        public string ValidEntryIndicator { get; set; }
        public Nullable<int> ctrPatientMedicalId { get; set; }
        public Nullable<int> ctrGyneHistoryId { get; set; }
        public Nullable<int> LogID { get; set; }
        public string MenopauseReason { get; set; }
        public string GynecHistoryOptionalDetails { get; set; }
        public string HormonesDescription { get; set; }
        public string GynecHistoryDetails { get; set; }
        public string RecentMammogramComment { get; set; }
        public string RecentPapSmearComment { get; set; }
        public string MenstrualDetails { get; set; }
        public string LatestTestDescription { get; set; }
        public string MedicalProblemDetails { get; set; }
        public string TreatmentDescription { get; set; }
        public string AgeAtProcedure { get; set; }
        public Nullable<long> DimDiagnosisCodeID { get; set; }
        public string MedicalHistoryValidEntryIndicator { get; set; }
        public string HormoneUseIndicator { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimDiagnosisCode DimDiagnosisCode { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimPatient DimPatient { get; set; }
    }
}
