//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPatientExam
    {
        public long FactPatientExamID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimUserID { get; set; }
        public Nullable<long> DimUserID_Approved { get; set; }
        public Nullable<long> DimDateID_ExamApprovedDateTime { get; set; }
        public Nullable<long> DimDateID_ExamDateTime { get; set; }
        public Nullable<long> DimDateID_DictationApprovedDateTime { get; set; }
        public string ApprovedIndicator { get; set; }
        public string ExamValidEntryIndicator { get; set; }
        public string BodySystemDescription { get; set; }
        public string ROSPEAssessmentDescription { get; set; }
        public Nullable<System.DateTime> ExamApprovedDateTime { get; set; }
        public Nullable<System.DateTime> ExamDateTime { get; set; }
        public Nullable<System.DateTime> DictationApprovedDateTime { get; set; }
        public string TransLogUserId { get; set; }
        public Nullable<System.DateTime> TransLogDateTime { get; set; }
        public string TransLogModifiedUserId { get; set; }
        public Nullable<System.DateTime> TransLogModifiedDateTime { get; set; }
        public Nullable<int> ctrpt_exam_id { get; set; }
        public Nullable<int> ctrpt_exam_system_id { get; set; }
        public Nullable<int> LogID { get; set; }
        public string ExamSystemValidEntryIndicator { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimUser DimUser { get; set; }
        public virtual DimUser DimUser1 { get; set; }
    }
}
