//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCourseDiagnosi
    {
        public long FactCourseDiagnosisID { get; set; }
        public long DimCourseID { get; set; }
        public long FactPatientDiagnosisID { get; set; }
        public long DimDiagnosisCodeID { get; set; }
        public Nullable<long> DimDxSiteID_BodySystem { get; set; }
        public Nullable<long> DimDxSiteID { get; set; }
        public Nullable<int> IsPrimary { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimCourse DimCourse { get; set; }
        public virtual DimDiagnosisCode DimDiagnosisCode { get; set; }
        public virtual DimDxSite DimDxSite { get; set; }
        public virtual DimDxSite DimDxSite1 { get; set; }
        public virtual FactPatientDiagnosi FactPatientDiagnosi { get; set; }
    }
}
