//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPatientLabResult
    {
        public long FactPatientLabResultID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimLookupID_UOM { get; set; }
        public Nullable<long> DimLookupID_StatusType { get; set; }
        public Nullable<long> DimLookupID_AbnormalFlagCode { get; set; }
        public Nullable<long> DimLookupID_SymbolCode { get; set; }
        public Nullable<long> DimLookupID_ComponentType { get; set; }
        public Nullable<long> DimLookupID_SpecimenRejectReason { get; set; }
        public Nullable<long> DimDateID_TestDateTime { get; set; }
        public string TypeOfTest { get; set; }
        public string ComponentName { get; set; }
        public Nullable<double> TestValue { get; set; }
        public Nullable<double> MinNorm { get; set; }
        public Nullable<double> MaxNorm { get; set; }
        public string TestValueStatusCode { get; set; }
        public string TestValueStatusDescription { get; set; }
        public Nullable<System.DateTime> TestDateTime { get; set; }
        public Nullable<double> MinReason { get; set; }
        public Nullable<double> MaxReason { get; set; }
        public string TestResultApprovedIndicator { get; set; }
        public string ProducerStakeholderId { get; set; }
        public string DspRefRange { get; set; }
        public string PatientId { get; set; }
        public Nullable<int> TestResultGroupId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> PatientVisitId { get; set; }
        public Nullable<int> TestResultId { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<long> DimLookupID_TestPriority { get; set; }
        public Nullable<System.DateTime> OrderedDateTime { get; set; }
        public Nullable<long> DimDateID_OrderedDateTime { get; set; }
        public Nullable<System.DateTime> TestRequestedDateTime { get; set; }
        public Nullable<long> DimDateID_TestRequestedDateTime { get; set; }
        public Nullable<long> DimLookupID_TestRequestType { get; set; }
        public Nullable<int> VerbalOrderId { get; set; }
        public string SentFlag { get; set; }
        public Nullable<long> DimUserID_Physician { get; set; }
        public Nullable<long> DimHospitalDepartmentID_Physician { get; set; }
        public string SpecimenIndicator { get; set; }
        public string TestValidEntryIndicator { get; set; }
        public string OrderApprovedIndicator { get; set; }
        public string ResultApprovedIndicator { get; set; }
        public string CancelIndicator { get; set; }
        public string AlertIndicator { get; set; }
        public string ErroredReason { get; set; }
        public Nullable<double> AbsoluteMaximum { get; set; }
        public Nullable<double> AbsoluteMinimum { get; set; }
        public string TestResultIndicator { get; set; }
        public string TestResultValue { get; set; }
        public string TransLogUserId { get; set; }
        public Nullable<System.DateTime> TransLogDateTime { get; set; }
        public string TransLogModifiedUserId { get; set; }
        public Nullable<System.DateTime> TransLogModifiedDateTime { get; set; }
        public string TestResultValidEntryIndicator { get; set; }
        public string FacilityGroupName { get; set; }
        public Nullable<long> DimActivityTransactionID { get; set; }
        public Nullable<long> DimHospitalDepartmentID_Facility { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string FacilityRequisitionId { get; set; }
        public string FacilityRequisitionDescription { get; set; }
        public string TestComponentFacilityName { get; set; }
        public string TestComment { get; set; }
        public string TestResultComment { get; set; }
        public string ProducerStakeholderName { get; set; }
        public Nullable<System.DateTime> CollectionStartDate { get; set; }
        public Nullable<long> DimDateID_CollectionStartDate { get; set; }
        public Nullable<System.DateTime> CollectionEndDate { get; set; }
        public Nullable<long> DimDateID_CollectionEndDate { get; set; }
        public Nullable<long> DimLookupID_SpecimenAction { get; set; }
        public Nullable<long> DimLookupID_SpecimenCondCode { get; set; }
        public string CollectedBy { get; set; }
        public string DangerCode { get; set; }
        public string ReleventClinicalInformation { get; set; }
        public Nullable<decimal> CollectionVolume { get; set; }
        public string TestResultGroupComment { get; set; }
        public string SpecimenSource { get; set; }
        public string PrimaryDX { get; set; }
        public string FacilityCategoryDescritpion { get; set; }
        public string TestOrderComment { get; set; }
        public Nullable<long> DimLookupID_CollectionVolumeUnit { get; set; }
        public string VitalIndicator { get; set; }
    
        public virtual DimActivityTransaction DimActivityTransaction { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimDate DimDate3 { get; set; }
        public virtual DimDate DimDate4 { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment { get; set; }
        public virtual DimHospitalDepartment DimHospitalDepartment1 { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        public virtual DimLookup DimLookup2 { get; set; }
        public virtual DimLookup DimLookup3 { get; set; }
        public virtual DimLookup DimLookup4 { get; set; }
        public virtual DimLookup DimLookup5 { get; set; }
        public virtual DimLookup DimLookup6 { get; set; }
        public virtual DimLookup DimLookup7 { get; set; }
        public virtual DimLookup DimLookup8 { get; set; }
        public virtual DimLookup DimLookup9 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimUser DimUser { get; set; }
    }
}
