//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPatientAllergy
    {
        public long FactPatientAllergyID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimLookupID_AllergyType { get; set; }
        public Nullable<long> DimLookupID_AllergySeverity { get; set; }
        public Nullable<long> DimDateID_AllergyStartedOn { get; set; }
        public string AllergicResponse { get; set; }
        public string AllergyDescription { get; set; }
        public string AllergicDrugDescription { get; set; }
        public string AllergicReaction { get; set; }
        public string AllergyTypeDesc { get; set; }
        public string AllergyCode { get; set; }
        public string AllergySeverityCode { get; set; }
        public string AllergySeverityDescripton { get; set; }
        public string AllergyAgentName { get; set; }
        public string AllergyComment { get; set; }
        public Nullable<int> ctrallergy_id { get; set; }
        public Nullable<int> LogID { get; set; }
        public string ValidEntryIndicator { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
    }
}
