//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactRxAdminAgtLevel
    {
        public long FactRxAdminAgtLevelID { get; set; }
        public long DimRxAgtID { get; set; }
        public int ctrRxAdminAgtLevelId { get; set; }
        public Nullable<int> RxAdminAgtLevelSequence { get; set; }
        public Nullable<long> RxAdminAgtStartDateID { get; set; }
        public Nullable<long> RxAdminAgtEndDateID { get; set; }
        public Nullable<int> RxAdminAgtNoDosesTaken { get; set; }
        public Nullable<decimal> RxAdminAgtDose { get; set; }
        public Nullable<long> RxAdminAgtDoseUnit_DimLookupID { get; set; }
        public Nullable<long> RxAdminAgtHowRecorded_DimLookupID { get; set; }
        public string RxAdminAgtValidEntry { get; set; }
        public Nullable<long> RxAdminAgtApprovedDatetimeID { get; set; }
        public Nullable<long> RxAdminAgtApprovedBy_DimUserID { get; set; }
        public Nullable<long> RxAdminAgtEnteredby_DimUserID { get; set; }
        public Nullable<System.DateTime> RxAdminAgtEnteredDatetime { get; set; }
        public Nullable<long> RxAdminAgtLastModifiedby_DimUserID { get; set; }
        public Nullable<System.DateTime> RxAdminAgtLastModifiedDatetime { get; set; }
        public string RxAdminAgtErrorReason { get; set; }
        public Nullable<int> LogID { get; set; }
    
        public virtual DimRxAgt DimRxAgt { get; set; }
    }
}
