//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactTreatmentHistory
    {
        public long FactTreatmentHistoryID { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimCourseID { get; set; }
        public Nullable<long> DimLookupID_TreatmentIntentType { get; set; }
        public Nullable<long> DimUserID_CompletedByUser { get; set; }
        public Nullable<long> DimLookupID_ClinicalStatus { get; set; }
        public Nullable<long> DimPlanID { get; set; }
        public Nullable<long> DimLookupID_PlanStatus { get; set; }
        public Nullable<long> DimUserID_StatusUser { get; set; }
        public Nullable<long> DimLookupID_FieldTechnique { get; set; }
        public Nullable<long> DimFieldID { get; set; }
        public Nullable<long> DimPlannedAddOnID1 { get; set; }
        public Nullable<long> DimPlannedAddOnID2 { get; set; }
        public Nullable<long> DimPlannedAddOnID3 { get; set; }
        public Nullable<long> DimPlannedAddOnID4 { get; set; }
        public Nullable<long> DimPlannedAddOnID5 { get; set; }
        public Nullable<long> DimPlanMachineID { get; set; }
        public Nullable<long> DimLookupID_Technique { get; set; }
        public Nullable<long> DimLookupID_TechniqueLabel { get; set; }
        public Nullable<long> DimLookupID_TreatmentDeliveryType { get; set; }
        public Nullable<long> DimActualMachineID { get; set; }
        public Nullable<long> DimTreatmentTransactionID { get; set; }
        public Nullable<long> DimUserID_UserName1 { get; set; }
        public Nullable<long> DimUserID_UserName2 { get; set; }
        public Nullable<long> DimUserID_UserName3 { get; set; }
        public Nullable<long> DimActualAddOnID1 { get; set; }
        public Nullable<long> DimActualAddOnID2 { get; set; }
        public Nullable<long> DimActualAddOnID3 { get; set; }
        public Nullable<long> DimActualAddOnID4 { get; set; }
        public Nullable<long> DimActualAddOnID5 { get; set; }
        public Nullable<long> DimActualAddOnID6 { get; set; }
        public Nullable<long> DimActualAddOnID7 { get; set; }
        public Nullable<long> DimActualAddOnID8 { get; set; }
        public Nullable<long> DimActualAddOnID9 { get; set; }
        public Nullable<long> DimActualAddOnID10 { get; set; }
        public Nullable<long> DimUserID_ApprovalUser { get; set; }
        public Nullable<long> DimUserID_MachineAuthorization { get; set; }
        public Nullable<long> DimPlannedEnergyID { get; set; }
        public Nullable<long> DimActualEnergyID { get; set; }
        public Nullable<long> DimDateID_CourseCompletedDateTime { get; set; }
        public Nullable<long> DimDateID_FirstTreatmentDate { get; set; }
        public Nullable<long> DimDateID_LastTreatmentDate { get; set; }
        public Nullable<long> DimDateID_PlanApprovedStatusDate { get; set; }
        public Nullable<long> DimDateID_AuthorizationDate { get; set; }
        public Nullable<long> DimDateID_CorrectionDateTime { get; set; }
        public Nullable<long> DimDateID_TreatmentEndTime { get; set; }
        public Nullable<long> DimDateID_TreatmentRecordDateTime { get; set; }
        public Nullable<long> DimDateID_TreatmentStartTime { get; set; }
        public Nullable<long> DimDateID_BreakPointDate { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<System.DateTime> FirstTreatmentDate { get; set; }
        public Nullable<System.DateTime> LastTreatmentDate { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsBrachy { get; set; }
        public Nullable<int> PlannedDoseRate { get; set; }
        public Nullable<double> PlannedMU { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public Nullable<long> DimUserID_AuthorizedBy { get; set; }
        public string OverrideParameters { get; set; }
        public Nullable<double> PlannedFieldDose { get; set; }
        public Nullable<double> DeliveredFieldDose { get; set; }
        public Nullable<System.DateTime> CorrectionDateTime { get; set; }
        public string RefPointId { get; set; }
        public string RefPointName { get; set; }
        public string DoseCorrectionComment { get; set; }
        public Nullable<double> CourseDoseDelivered { get; set; }
        public Nullable<double> CourseDosePlanned { get; set; }
        public Nullable<double> CourseDoseRemaining { get; set; }
        public Nullable<double> OtherCourseDoseDelivered { get; set; }
        public Nullable<double> DoseCorrection { get; set; }
        public Nullable<double> TotalDoseLimit { get; set; }
        public Nullable<double> DailyDoseLimit { get; set; }
        public Nullable<double> SessionDoseLimit { get; set; }
        public Nullable<System.DateTime> BreakPointDate { get; set; }
        public Nullable<double> BreakPointDose { get; set; }
        public string BreakPointNote { get; set; }
        public Nullable<int> BreakPointNum { get; set; }
        public Nullable<int> NoTxSessionRemaining { get; set; }
        public Nullable<int> NoTxSessionPlanned { get; set; }
        public Nullable<int> NoTxSessionDelivered { get; set; }
        public Nullable<int> PrimaryFlag { get; set; }
        public Nullable<int> FractionsDelivered { get; set; }
        public Nullable<int> FractionsPlanned { get; set; }
        public Nullable<int> FractionsRemaining { get; set; }
        public Nullable<double> DosePerFraction { get; set; }
        public Nullable<double> DoseDelivered { get; set; }
        public Nullable<double> DoseRemainingInFraction { get; set; }
        public Nullable<double> RunningPartial { get; set; }
        public Nullable<double> DosePredictedMax { get; set; }
        public Nullable<double> DosePredictedMin { get; set; }
        public Nullable<double> DosePredicted { get; set; }
        public Nullable<double> DosePredictedInOtherCourses { get; set; }
        public Nullable<double> DoseRemaining { get; set; }
        public Nullable<double> DoseRemainingMax { get; set; }
        public Nullable<double> DoseRemainingMin { get; set; }
        public Nullable<int> ActualDoseRate { get; set; }
        public Nullable<double> TreatmentTime { get; set; }
        public Nullable<double> DeliveredMU { get; set; }
        public Nullable<double> DoseDeliveredToPrimaryRefPoint { get; set; }
        public string PFFlag { get; set; }
        public Nullable<byte> PFMUSubFlag { get; set; }
        public string PIFlag { get; set; }
        public Nullable<System.DateTime> TreatmentEndTime { get; set; }
        public Nullable<System.DateTime> TreatmentRecordDateTime { get; set; }
        public Nullable<System.DateTime> TreatmentStartTime { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> CorrelatedEventNumber { get; set; }
        public Nullable<int> EventNumber { get; set; }
        public Nullable<double> FieldMUActual { get; set; }
        public string FieldStatus { get; set; }
        public Nullable<int> IntendedNumOfPaintings { get; set; }
        public Nullable<byte> IsImage { get; set; }
        public Nullable<int> NoFractions { get; set; }
        public Nullable<int> NoOfFractions { get; set; }
        public Nullable<int> NoOfImage { get; set; }
        public Nullable<int> PrintFlag { get; set; }
        public Nullable<int> RadiationNumber { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<byte> RVFlag { get; set; }
        public string TerminationStatus { get; set; }
        public Nullable<double> DistalEndEnergy { get; set; }
        public Nullable<double> DoseDelta { get; set; }
        public Nullable<int> FractionNumber { get; set; }
        public Nullable<double> DoseDeliveredPerFraction { get; set; }
        public Nullable<System.DateTime> LastChartQADate { get; set; }
        public Nullable<long> ctrChartQATreatmentSer { get; set; }
        public Nullable<long> ctrPhysicianIntentSer { get; set; }
        public Nullable<long> ctrRefPointLogSer { get; set; }
        public Nullable<long> ctrDoseCorrectionLogSer { get; set; }
        public Nullable<long> ctrTechniqueSer { get; set; }
        public Nullable<long> ctrPatientVolumeSer { get; set; }
        public Nullable<long> ctrRefPointSer { get; set; }
        public Nullable<long> ctrBreakPointSer { get; set; }
        public Nullable<long> ctrPrescriptionSer { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<double> TreatmentStartTimeFloatValue { get; set; }
    
        public virtual DimAddOn DimAddOn { get; set; }
        public virtual DimAddOn DimAddOn1 { get; set; }
        public virtual DimAddOn DimAddOn2 { get; set; }
        public virtual DimAddOn DimAddOn3 { get; set; }
        public virtual DimAddOn DimAddOn4 { get; set; }
        public virtual DimAddOn DimAddOn5 { get; set; }
        public virtual DimAddOn DimAddOn6 { get; set; }
        public virtual DimAddOn DimAddOn7 { get; set; }
        public virtual DimAddOn DimAddOn8 { get; set; }
        public virtual DimAddOn DimAddOn9 { get; set; }
        public virtual DimAddOn DimAddOn10 { get; set; }
        public virtual DimAddOn DimAddOn11 { get; set; }
        public virtual DimAddOn DimAddOn12 { get; set; }
        public virtual DimAddOn DimAddOn13 { get; set; }
        public virtual DimAddOn DimAddOn14 { get; set; }
        public virtual DimCourse DimCourse { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimDate DimDate3 { get; set; }
        public virtual DimDate DimDate4 { get; set; }
        public virtual DimDate DimDate5 { get; set; }
        public virtual DimDate DimDate6 { get; set; }
        public virtual DimDate DimDate7 { get; set; }
        public virtual DimDate DimDate8 { get; set; }
        public virtual DimDate DimDate9 { get; set; }
        public virtual DimEnergy DimEnergy { get; set; }
        public virtual DimEnergy DimEnergy1 { get; set; }
        public virtual DimField DimField { get; set; }
        public virtual DimLookup DimLookup { get; set; }
        public virtual DimLookup DimLookup1 { get; set; }
        public virtual DimLookup DimLookup2 { get; set; }
        public virtual DimLookup DimLookup3 { get; set; }
        public virtual DimLookup DimLookup4 { get; set; }
        public virtual DimLookup DimLookup5 { get; set; }
        public virtual DimLookup DimLookup6 { get; set; }
        public virtual DimMachine DimMachine { get; set; }
        public virtual DimMachine DimMachine1 { get; set; }
        public virtual DimPatient DimPatient { get; set; }
        public virtual DimPlan DimPlan { get; set; }
        public virtual DimTreatmentTransaction DimTreatmentTransaction { get; set; }
        public virtual DimUser DimUser { get; set; }
        public virtual DimUser DimUser1 { get; set; }
        public virtual DimUser DimUser2 { get; set; }
        public virtual DimUser DimUser3 { get; set; }
        public virtual DimUser DimUser4 { get; set; }
        public virtual DimUser DimUser5 { get; set; }
        public virtual DimUser DimUser6 { get; set; }
        public virtual DimUser DimUser7 { get; set; }
    }
}
