//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class InSightiveActivitiesConfiguration
    {
        public int ID { get; set; }
        public long DimActivityID { get; set; }
        public string ActivityCategory { get; set; }
        public string ActivityName { get; set; }
        public Nullable<short> ActivityOrder { get; set; }
    
        public virtual DimActivity DimActivity { get; set; }
    }
}
