//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class InSightiveResourceMachine
    {
        public long DimResourceID { get; set; }
        public long ActualResourceID { get; set; }
        public string ResourceType { get; set; }
        public string ResourceTypeENU { get; set; }
        public Nullable<long> ctrResourceSer { get; set; }
        public long DimMachineID { get; set; }
        public string MachineFullName { get; set; }
        public string MachineId { get; set; }
        public string MachineAliasName { get; set; }
        public string MachineType { get; set; }
        public string MachineScale { get; set; }
        public string MachineModel { get; set; }
        public string ResourceObjectStatus { get; set; }
        public string MachineObjectStatusENU { get; set; }
        public string MachineObjectStatus { get; set; }
    }
}
