//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverrideModel
    {
        public long ID { get; set; }
        public Nullable<long> PatientSer { get; set; }
        public string OverrideParameters { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public Nullable<long> CourseSer { get; set; }
        public string CourseId { get; set; }
        public Nullable<long> PlanSetupSer { get; set; }
        public string PlanSetupId { get; set; }
        public Nullable<long> RadiationSer { get; set; }
        public Nullable<double> DoseDelta { get; set; }
        public Nullable<long> PatientVolumeSer { get; set; }
        public Nullable<long> RefPointSer { get; set; }
        public Nullable<long> RefPointLogSer { get; set; }
        public Nullable<long> RTPlanSer { get; set; }
    }
}
