//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannedAddOn_FullMig
    {
        public string AddOnId { get; set; }
        public Nullable<long> RadiationSer { get; set; }
        public Nullable<long> DimMachineID { get; set; }
        public Nullable<long> Rownum { get; set; }
        public Nullable<long> MachineSer { get; set; }
        public Nullable<long> DimAddOnID { get; set; }
    }
}
