//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefPointModel
    {
        public long ID { get; set; }
        public string CourseId { get; set; }
        public string PlanSetupId { get; set; }
        public string RefPointId { get; set; }
        public string RefPointName { get; set; }
        public Nullable<double> CourseDosePlanned { get; set; }
        public Nullable<double> CourseDoseDelivered { get; set; }
        public Nullable<double> CourseDoseRemaining { get; set; }
        public Nullable<double> OtherCourseDoseDelivered { get; set; }
        public Nullable<double> DosePredictedInOtherCourses { get; set; }
        public Nullable<double> DoseCorrection { get; set; }
        public Nullable<double> TotalDoseLimit { get; set; }
        public Nullable<double> DailyDoseLimit { get; set; }
        public Nullable<double> SessionDoseLimit { get; set; }
        public Nullable<double> BreakPointDose { get; set; }
        public Nullable<System.DateTime> BreakPointDate { get; set; }
        public string BreakPointNote { get; set; }
        public Nullable<int> NoTxSessionRemaining { get; set; }
        public Nullable<int> NoTxSessionPlanned { get; set; }
        public Nullable<int> NoTxSessionDelivered { get; set; }
        public Nullable<int> PrimaryFlag { get; set; }
        public Nullable<int> FractionsDelivered { get; set; }
        public Nullable<int> FractionsPlanned { get; set; }
        public Nullable<int> FractionsRemaining { get; set; }
        public Nullable<double> DosePerFraction { get; set; }
        public Nullable<double> DoseDelivered { get; set; }
        public Nullable<double> DoseRemainingInFraction { get; set; }
        public Nullable<double> RunningPartial { get; set; }
        public Nullable<double> DoseRemainingMax { get; set; }
        public Nullable<double> DoseRemainingMin { get; set; }
        public Nullable<double> DoseRemaining { get; set; }
        public Nullable<double> DosePredictedMax { get; set; }
        public Nullable<double> DosePredictedMin { get; set; }
        public Nullable<double> DosePredicted { get; set; }
        public Nullable<int> BreakPointNum { get; set; }
        public Nullable<long> PatientSer { get; set; }
        public Nullable<long> CourseSer { get; set; }
        public Nullable<long> PlanSetupSer { get; set; }
        public Nullable<long> RefPointSer { get; set; }
        public Nullable<long> RTPlanSer { get; set; }
        public Nullable<long> BreakPointSer { get; set; }
    }
}
