//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationModel
    {
        public long ID { get; set; }
        public Nullable<long> PatientSer { get; set; }
        public string PatientId { get; set; }
        public Nullable<long> CourseSer { get; set; }
        public Nullable<long> RTPlanSer { get; set; }
        public string RTPlanId { get; set; }
        public Nullable<long> RadiationSer { get; set; }
        public string RadiationId { get; set; }
        public Nullable<long> RefImageSer { get; set; }
        public string RefImageId { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalTime { get; set; }
        public string ApprovalStatus { get; set; }
        public string MachineId { get; set; }
        public string RegistrationType { get; set; }
        public Nullable<long> PlanSetupSer { get; set; }
        public Nullable<long> ResourceSer { get; set; }
        public Nullable<long> SeriesSer { get; set; }
    }
}
