//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticLog
    {
        public int LogID { get; set; }
        public string ComponentName { get; set; }
        public Nullable<int> Rows { get; set; }
        public Nullable<int> TimeMS { get; set; }
        public Nullable<int> MinRowsPerSec { get; set; }
        public Nullable<int> MeanRowsPerSec { get; set; }
        public Nullable<int> MaxRowsPerSec { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
    }
}
