//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class stgDimActivityTransaction
    {
        public long ctrScheduledActivitySer { get; set; }
        public long ctrActivityInstanceSer { get; set; }
        public long ctrResourceSer { get; set; }
        public Nullable<long> DimDateID_CreationDate { get; set; }
        public Nullable<int> AppointmentInstanceFlag { get; set; }
        public Nullable<System.DateTime> ActivityStartDateTime { get; set; }
        public Nullable<System.DateTime> ActivityEndDateTime { get; set; }
        public Nullable<System.DateTime> ScheduledEndTime { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public Nullable<long> DimDateID_ScheduledEndTime { get; set; }
        public Nullable<long> DimDateID_AppointmentDateTime { get; set; }
        public Nullable<long> DimDateID_ActivityStartDateTime { get; set; }
        public Nullable<long> DimDateID_ActivityEndDateTime { get; set; }
        public Nullable<System.DateTime> DerivedAppointmentTaskDate { get; set; }
        public string AppointmentStatus { get; set; }
        public string AppointmentResourceStatus { get; set; }
        public Nullable<long> DimLookupID_AppointmentResourceStatus { get; set; }
        public Nullable<long> DimLookupID_AppointmentStatus { get; set; }
    }
}
