//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMetaData
    {
        public long TableMetaDataID { get; set; }
        public string DimTableName { get; set; }
        public string TablePrimaryIDColumn { get; set; }
        public string TableLookupCodeColumn { get; set; }
        public string TableLookupTypeColumn { get; set; }
        public string TableColumnToMap { get; set; }
    }
}
