//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempstgDimPatient
    {
        public Nullable<long> PatientSer { get; set; }
        public string pt_id { get; set; }
        public Nullable<int> IsDuplicatePatientSer { get; set; }
        public int Id { get; set; }
    }
}
