//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempInterpolationDVHData
    {
        public long ID { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> DoseValue { get; set; }
        public Nullable<double> RelativeVolume { get; set; }
        public Nullable<long> DimPatientID { get; set; }
        public Nullable<long> DimPlanID { get; set; }
        public Nullable<long> DimStructureID { get; set; }
    }
}
